---
permalink: sg6000/optional-changing-raid-mode-sg6000-only.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: 'Vous pouvez passer à un autre mode RAID sur l"appliance pour répondre à vos besoins en termes de stockage et de restauration. Vous ne pouvez modifier le mode qu"avant de déployer l"appliance Storage Node.' 
---
= Facultatif : modification du mode RAID (SG6000 uniquement)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez passer à un autre mode RAID sur l'appliance pour répondre à vos besoins en termes de stockage et de restauration. Vous ne pouvez modifier le mode qu'avant de déployer l'appliance Storage Node.

.Ce dont vous avez besoin, 8217;ll
* Vous utilisez n'importe quel client pouvant vous connecter à StorageGRID.
* Le client a un xref:../admin/web-browser-requirements.adoc[navigateur web pris en charge].


Avant de déployer l'appliance en tant que nœud de stockage, vous pouvez choisir l'une des options de configuration de volume suivantes :

* *DDP* : ce mode utilise deux lecteurs de parité pour chaque huit lecteurs de données. Il s'agit du mode par défaut et recommandé pour tous les appareils. Par rapport à RAID6, les DDP offrent de meilleures performances du système, des temps de reconstruction réduits après une panne de disque et une gestion simplifiée.
* *DDP16* : ce mode utilise deux disques de parité pour chaque 16 disques de données, ce qui améliore l'efficacité du stockage par rapport au pool DDP. Par rapport à RAID6 mais, le DDP16 améliore les performances du système et réduit les délais de reconstruction après une panne de disque, la facilité de gestion et l'efficacité du stockage équivalente. Pour utiliser le mode DDP16, votre configuration doit contenir au moins 20 lecteurs. Le DDP16 n'offre pas de protection contre les pertes de tiroirs.
* *RAID6* : ce mode utilise deux lecteurs de parité pour chaque disque de données de 16 ou plus. Pour utiliser le mode RAID 6, votre configuration doit contenir au moins 20 lecteurs. RAID 6 peut augmenter l'efficacité du stockage de l'appliance par rapport aux pools de disques dynamiques. Cependant, il n'est pas recommandé d'utiliser la plupart des environnements StorageGRID.



IMPORTANT: Si un volume a déjà été configuré ou si StorageGRID a été installé précédemment, la modification du mode RAID entraîne le retrait et le remplacement des volumes. Toutes les données présentes sur ces volumes seront perdues.

.Étapes
. Ouvrez un navigateur et entrez l'une des adresses IP du contrôleur de calcul de l'appliance.
+
`*https://_Controller_IP_:8443*`

+
`_Controller_IP_` Est l'adresse IP du contrôleur de calcul (pas le contrôleur de stockage) sur l'un des trois réseaux StorageGRID.

+
La page d'accueil du programme d'installation de l'appliance StorageGRID s'affiche.

. Sélectionnez *Advanced* *RAID mode*.
. Sur la page *configurer le mode RAID*, sélectionnez le mode RAID souhaité dans la liste déroulante mode.
. Cliquez sur *Enregistrer*.


http://mysupport.netapp.com/info/web/ECMP1658252.html["Site de documentation sur les systèmes NetApp E-Series"^]
