---
permalink: sg6000/unable-to-connect-to-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection 
summary: 'Si vous ne parvenez pas à vous connecter à l"appliance, il se peut qu"il y ait un problème de réseau ou que l"installation du matériel n"ait pas été correctement effectuée.' 
---
= Connexion à l'appareil impossible
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous ne parvenez pas à vous connecter à l'appliance, il se peut qu'il y ait un problème de réseau ou que l'installation du matériel n'ait pas été correctement effectuée.

.Étapes
. Si vous ne pouvez pas vous connecter à SANtricity System Manager :
+
.. Essayez d'envoyer une requête ping à l'appliance en utilisant l'adresse IP de l'un des contrôleurs de stockage du réseau de gestion pour SANtricity System Manager : +
`*ping _Storage_Controller_IP_*`
.. Si vous ne recevez aucune réponse de la commande ping, confirmez que vous utilisez la bonne adresse IP.
+
Utilisez l'adresse IP pour le port de gestion 1 de l'un des contrôleurs de stockage.

.. Si l'adresse IP est correcte, vérifiez le câblage du dispositif et la configuration du réseau.
+
Si ce n'est pas le cas, contactez le support technique.

.. Si la commande ping a réussi, ouvrez un navigateur Web.
.. Entrez l'URL pour SANtricity System Manager : +
`*https://_Storage_Controller_IP_*`
+
La page de connexion à SANtricity System Manager s'affiche.



. Si vous ne parvenez pas à vous connecter au contrôleur SG6000-CN :
+
.. Essayez d'envoyer une requête ping à l'appareil à l'aide de l'adresse IP du contrôleur SG6000-CN : +
`*ping _SG6000-CN_Controller_IP_*`
.. Si vous ne recevez aucune réponse de la commande ping, confirmez que vous utilisez la bonne adresse IP.
+
Vous pouvez utiliser l'adresse IP de l'appliance sur le réseau Grid, le réseau Admin ou le réseau client.

.. Si l'adresse IP est correcte, vérifiez le câblage de l'appliance, les émetteurs-récepteurs SFP et la configuration du réseau.
.. Si l'accès physique au SG6000-CN est disponible, vous pouvez utiliser une connexion directe à l'adresse IP locale de liaison permanente `169.254.0.1` pour vérifier la configuration de la mise en réseau du contrôleur et la mettre à jour si nécessaire. Pour obtenir des instructions détaillées, reportez-vous à l'étape 2 de la section xref:..//sg6000/accessing-storagegrid-appliance-installer-sg6000.adoc[Accès au programme d'installation de l'appliance StorageGRID].
+
Si ce n'est pas le cas, contactez le support technique.

.. Si la commande ping a réussi, ouvrez un navigateur Web.
.. Entrez l'URL du programme d'installation de l'appliance StorageGRID : +
`*https://_SG6000-CN_Controller_IP_:8443*`
+
La page d'accueil s'affiche.




