---
permalink: audit/client-read-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client read, SGET, SHEA, WGET, WHEA, S3, swift 
summary: 'Les messages d"audit de lecture des clients sont consignés lorsqu"une application client S3 ou Swift demande de récupérer un objet.' 
---
= Messages d'audit de lecture du client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les messages d'audit de lecture des clients sont consignés lorsqu'une application client S3 ou Swift demande de récupérer un objet.

|===
| Code | Description | Utilisé par | Voir 


 a| 
SGET
 a| 
S3 GET : log une transaction réussie pour récupérer un objet ou répertorier les objets dans un compartiment.

*Remarque :* si la transaction fonctionne sur une sous-ressource, le message d'audit inclura le champ S3SR.
 a| 
Client S3
 a| 
xref:sget-s3-get.adoc[SGET : OBTENEZ S3]



 a| 
SHEA
 a| 
TÊTE S3 : consigne une transaction réussie pour vérifier l'existence d'un objet ou d'un compartiment.
 a| 
Client S3
 a| 
xref:shea-s3-head.adoc[SHEA : TÊTE S3]



 a| 
C'EST PARTI
 a| 
SWIFT GET : log une transaction réussie pour récupérer un objet ou répertorier les objets dans un conteneur.
 a| 
Client Swift
 a| 
xref:wget-swift-get.adoc[WGET: SWIFT GET]



 a| 
WHEA
 a| 
SWIFT HEAD : consigne une transaction réussie afin de vérifier l'existence d'un objet ou d'un conteneur.
 a| 
Client Swift
 a| 
xref:whea-swift-head.adoc[WHEA: TÊTE SWIFT]

|===