---
permalink: audit/object-delete-transactions.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, transaction, transactions, Object delete, S3 delete, Swift delete, S3, Swift, SDEL, WDEL 
summary: 'Vous pouvez identifier les transactions de suppression d"objets dans le journal d"audit en localisant les messages d"audit spécifiques à l"API \(S3 et Swift\).' 
---
= Transactions de suppression d'objet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez identifier les transactions de suppression d'objets dans le journal d'audit en localisant les messages d'audit spécifiques aux API (S3 et Swift).

Tous les messages d'audit générés lors d'une opération de suppression ne sont pas répertoriés dans les tableaux suivants. Seuls les messages requis pour suivre la transaction de suppression sont inclus.



== S3 supprime les messages d'audit

|===
| Code | Nom | Description | Tracé | Voir 


 a| 
SDEL
 a| 
Suppression S3
 a| 
Demande de suppression de l'objet d'un compartiment.
 a| 
CBID, S3KY
 a| 
xref:sdel-s3-delete.adoc[SDEL : SUPPRESSION S3]

|===


== Supprimez les messages d'audit Swift

|===
| Code | Nom | Description | Tracé | Voir 


 a| 
WDEL
 a| 
Suppression Swift
 a| 
Demande de suppression de l'objet d'un conteneur ou du conteneur.
 a| 
CBID, WOBJ
 a| 
xref:wdel-swift-delete.adoc[WDEL : SUPPRESSION rapide]

|===