---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid-116
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - version-number: '11.6'
    url: "/storagegrid-116"
  - version-number: '11.9'
    url: "/storagegrid"
  - version-number: '11.8'
    url: "/storagegrid-118"
  - version-number: '11.7'
    url: "/storagegrid-117"
  - version-number: '11.5'
    url: "/storagegrid-115"
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents relatifs à StorageGRID 11.6
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release-notes/index.html"
  - title: Commencez
    entries:
    - section: primer
    - section: network
  - title: Installer et entretenir le matériel de l'appareil
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: Installez et mettez à niveau le logiciel
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: Administrer le système
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utiliser StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Contrôler et gérer StorageGRID
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: Activez StorageGRID
    url: "/storagegrid-enable.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
