---
permalink: upgrade/docker-image-availability-check-error-messages.html 
sidebar: sidebar 
keywords: upgrade, error message, docker image availability 
summary: 'Lorsque vous tentez de démarrer le processus de mise à niveau, un message d"erreur indiquant "les problèmes suivants ont été identifiés par la suite de validation des contrôles de disponibilité des images Docker" peut s"afficher. Tous les problèmes doivent être résolus avant la fin de la mise à niveau.' 
---
= Messages d'erreur "contrôle de disponibilité des images Docker"
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous tentez de démarrer le processus de mise à niveau, un message d'erreur indiquant « les problèmes suivants ont été identifiés par la suite de validation des contrôles de disponibilité des images Docker » s'affiche. Tous les problèmes doivent être résolus avant la fin de la mise à niveau.

Contactez le support technique si vous n'êtes pas certain des modifications requises pour résoudre les problèmes identifiés.

[cols="1a,1a,1a"]
|===
| Messagerie | Cause | Solution 


 a| 
Impossible de déterminer la version de la mise à niveau. Mettre à niveau le fichier d'informations de version `{file_path}` ne correspond pas au format attendu.
 a| 
Le package de mise à niveau est corrompu.
 a| 
Téléchargez à nouveau le package de mise à niveau, puis réessayez. Si le problème persiste, contactez le support technique.



 a| 
Mettre à niveau le fichier d'informations de version `{file_path}` n'a pas été trouvé. Impossible de déterminer la version de la mise à niveau.
 a| 
Le package de mise à niveau est corrompu.
 a| 
Téléchargez à nouveau le package de mise à niveau, puis réessayez. Si le problème persiste, contactez le support technique.



 a| 
Impossible de déterminer la version de version actuellement installée sur `{node_name}`.
 a| 
Un fichier critique du nœud est corrompu.
 a| 
Contactez l'assistance technique.



 a| 
Erreur de connexion lors de la tentative de liste des versions sur `{node_name}`
 a| 
Le nœud est hors ligne ou la connexion a été interrompue.
 a| 
Vérifiez que tous les nœuds sont en ligne et accessibles depuis le nœud d'administration principal, puis réessayez.



 a| 
Hôte pour le nœud `{node_name}` N'a pas de StorageGRID `{upgrade_version}` image chargée. Les images et les services doivent être installés sur l'hôte avant que la mise à niveau ne puisse se poursuivre.
 a| 
Les packages RPM ou DEB pour la mise à niveau n'ont pas été installés sur l'hôte sur lequel le nœud est en cours d'exécution, ou les images sont toujours en cours d'importation.

*Remarque :* cette erreur s'applique uniquement aux nœuds qui s'exécutent en tant que conteneurs sous Linux.
 a| 
Assurez-vous que les packages RPM ou DEB ont été installés sur tous les hôtes Linux sur lesquels des nœuds sont exécutés. Assurez-vous que la version est correcte pour le service et le fichier d'images. Attendez quelques minutes, puis réessayez.

Voir xref:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.adoc[Linux : installez le package RPM ou DEB sur tous les hôtes].



 a| 
Erreur lors de la vérification du nœud `{node_name}`
 a| 
Une erreur inattendue s'est produite.
 a| 
Attendez quelques minutes, puis réessayez.



 a| 
Erreur de suppression lors de l'exécution de contrôles préalables. `{error_string}`
 a| 
Une erreur inattendue s'est produite.
 a| 
Attendez quelques minutes, puis réessayez.

|===