---
permalink: sg100-1000/automating-installation-configuration-appliance-nodes-configure-sga-py-script.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, automate, automating, automation, automatic, install, installation, configuration, configure, configure-sga.py script, configure-sga.py 
summary: 'Vous pouvez utiliser le script configure-sga.py pour automatiser la plupart des tâches d"installation et de configuration des nœuds de l"appliance StorageGRID, y compris l"installation et la configuration d"un nœud d"administration principal. Ce script peut être utile si vous avez un grand nombre d"appliances à configurer. Vous pouvez également utiliser le script pour générer un fichier JSON qui contient les informations de configuration de l"appliance.' 
---
= Automatisez l'installation et la configuration des nœuds d'appliance à l'aide du script configure-sga.py
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `configure-sga.py` Script permettant d'automatiser la plupart des tâches d'installation et de configuration des nœuds d'appliance StorageGRID, notamment l'installation et la configuration d'un nœud d'administration principal. Ce script peut être utile si vous avez un grand nombre d'appliances à configurer. Vous pouvez également utiliser le script pour générer un fichier JSON qui contient les informations de configuration de l'appliance.

.Ce dont vous avez besoin
* L'appliance a été installée dans un rack, connectée à vos réseaux et sous tension.
* Les liens réseau et les adresses IP ont été configurés pour le nœud d'administration principal à l'aide du programme d'installation de l'appliance StorageGRID.
* Si vous installez le noeud d'administration principal, vous connaissez son adresse IP.
* Si vous installez et configurez d'autres nœuds, le nœud d'administration principal a été déployé et vous connaissez son adresse IP.
* Pour tous les nœuds autres que le nœud d'administration principal, tous les sous-réseaux de réseau Grid répertoriés dans la page Configuration IP du programme d'installation de l'appliance StorageGRID ont été définis dans la liste de sous-réseaux de réseau Grid sur le nœud d'administration principal.
* Vous avez téléchargé le `configure-sga.py` fichier. Le fichier est inclus dans l'archive d'installation ou vous pouvez y accéder en cliquant sur *aide* *script d'installation de l'appliance* dans le programme d'installation de l'appliance StorageGRID.



NOTE: Cette procédure est destinée aux utilisateurs avancés disposant d'une certaine expérience en utilisant des interfaces de ligne de commande. C'est également possible xref:automating-appliance-configuration-using-storagegrid-appliance-installer.adoc[Utilisez le programme d'installation de l'appliance StorageGRID pour automatiser la configuration].

.Étapes
. Connectez-vous à la machine Linux que vous utilisez pour exécuter le script Python.
. Pour obtenir de l'aide générale sur la syntaxe du script et pour afficher la liste des paramètres disponibles, entrez les informations suivantes :
+
[listing]
----
configure-sga.py --help
----
+
Le `configure-sga.py` script utilise cinq sous-commandes :

+
** `advanced` Pour les interactions avancées avec l'appliance StorageGRID, notamment la configuration BMC, et la création d'un fichier JSON contenant la configuration actuelle de l'appliance
** `configure` Pour configurer le mode RAID, le nom du nœud et les paramètres réseau
** `install` Pour démarrer une installation StorageGRID
** `monitor` Pour contrôler une installation StorageGRID
** `reboot` pour redémarrer l'appliance
+
Si vous entrez une sous-commande (avancé, configurez, installez, surveillez ou redémarrez), suivie de l'argument `--help` option vous obtenez un autre texte d'aide fournissant plus de détails sur les options disponibles dans cette sous-commande : +
`configure-sga.py _subcommand_ --help`



. Pour vérifier la configuration actuelle du nœud de l'appliance, entrez l'emplacement suivant `_SGA-install-ip_` Est l'une des adresses IP du noeud de l'appliance : +
`configure-sga.py configure _SGA-INSTALL-IP_`
+
Les résultats indiquent les informations IP actuelles de l'appliance, y compris l'adresse IP du noeud d'administration principal et les informations sur les réseaux Admin, Grid et client.

+
[listing]
----
Connecting to +https://10.224.2.30:8443+ (Checking version and connectivity.)
2021/02/25 16:25:11: Performing GET on /api/versions... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/system-info... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/admin-connection... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/link-config... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/networks... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/system-config... Received 200

  StorageGRID Appliance
    Name:        LAB-SGA-2-30
    Node type:   storage

  StorageGRID primary Admin Node
    IP:        172.16.1.170
    State:     unknown
    Message:   Initializing...
    Version:   Unknown

  Network Link Configuration
    Link Status
          Link      State      Speed (Gbps)
          ----      -----      -----
          1         Up         10
          2         Up         10
          3         Up         10
          4         Up         10
          5         Up         1
          6         Down       N/A

    Link Settings
        Port bond mode:      FIXED
        Link speed:          10GBE

        Grid Network:        ENABLED
            Bonding mode:    active-backup
            VLAN:            novlan
            MAC Addresses:   00:a0:98:59:8e:8a  00:a0:98:59:8e:82

        Admin Network:       ENABLED
            Bonding mode:    no-bond
            MAC Addresses:   00:80:e5:29:70:f4

        Client Network:      ENABLED
            Bonding mode:    active-backup
            VLAN:            novlan
            MAC Addresses:   00:a0:98:59:8e:89  00:a0:98:59:8e:81

  Grid Network
    CIDR:      172.16.2.30/21 (Static)
    MAC:       00:A0:98:59:8E:8A
    Gateway:   172.16.0.1
    Subnets:   172.17.0.0/21
               172.18.0.0/21
               192.168.0.0/21
    MTU:       1500

  Admin Network
    CIDR:      10.224.2.30/21 (Static)
    MAC:       00:80:E5:29:70:F4
    Gateway:   10.224.0.1
    Subnets:   10.0.0.0/8
               172.19.0.0/16
               172.21.0.0/16
    MTU:       1500

  Client Network
    CIDR:      47.47.2.30/21 (Static)
    MAC:       00:A0:98:59:8E:89
    Gateway:   47.47.0.1
    MTU:       2000

##############################################################
#####   If you are satisfied with this configuration,    #####
##### execute the script with the "install" sub-command. #####
##############################################################
----
. Si vous devez modifier l'une des valeurs de la configuration actuelle, utilisez le `configure` sous-commande pour les mettre à jour. Par exemple, si vous souhaitez modifier l'adresse IP utilisée par l'appliance pour la connexion au nœud d'administration principal à `172.16.2.99`, entrez les informations suivantes : +
`configure-sga.py configure --admin-ip 172.16.2.99 _SGA-INSTALL-IP_`
. Pour sauvegarder la configuration de l'appliance dans un fichier JSON, utilisez les fonctionnalités avancées et `backup-file` sous-commandes. Par exemple, si vous souhaitez sauvegarder la configuration d'une appliance avec une adresse IP `_SGA-INSTALL-IP_` à un fichier nommé `appliance-SG1000.json`, entrez les informations suivantes : +
`configure-sga.py advanced --backup-file appliance-SG1000.json _SGA-INSTALL-IP_`
+
Le fichier JSON contenant les informations de configuration est écrit dans le même répertoire que celui où vous avez exécuté le script à partir de.

+

IMPORTANT: Vérifiez que le nom de nœud supérieur dans le fichier JSON généré correspond au nom de l'appliance. Ne modifiez pas ce fichier sauf si vous êtes un utilisateur expérimenté et que vous comprenez parfaitement les API StorageGRID.

. Lorsque vous êtes satisfait de la configuration de l'appliance, utilisez le `install` et `monitor` sous-commandes pour installer l'appliance : +
`configure-sga.py install --monitor _SGA-INSTALL-IP_`
. Si vous souhaitez redémarrer l'appareil, entrez les valeurs suivantes : +
`configure-sga.py reboot _SGA-INSTALL-IP_`

