---
permalink: sg100-1000/configuring-snmp-settings-for-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, SNMP, configure, setup, set up 
summary: 'Si vous êtes familier avec la configuration de SNMP pour le matériel, vous pouvez utiliser l"interface BMC pour configurer les paramètres SNMP pour l"appliance services. Vous pouvez fournir des chaînes de communauté sécurisées, activer le Trap SNMP et spécifier jusqu"à cinq destinations SNMP.' 
---
= Configurez les paramètres SNMP pour l'appliance de services
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous êtes familier avec la configuration de SNMP pour le matériel, vous pouvez utiliser l'interface BMC pour configurer les paramètres SNMP pour l'appliance services. Vous pouvez fournir des chaînes de communauté sécurisées, activer le Trap SNMP et spécifier jusqu'à cinq destinations SNMP.

.Ce dont vous avez besoin, 8217;ll
* Vous savez comment accéder au tableau de bord BMC.
* Vous avez de l'expérience dans la configuration des paramètres SNMP pour les équipements SNMPv1-v2c.



NOTE: Les paramètres BMC définis lors de cette procédure peuvent ne pas être préservés en cas de défaillance de l'appliance et doivent être remplacés. Assurez-vous d'avoir un enregistrement de tous les paramètres que vous avez appliqués afin de pouvoir les réappliquer facilement après un remplacement de matériel si nécessaire.

.Étapes
. Dans le tableau de bord BMC, sélectionnez *Paramètres* *Paramètres SNMP*.
. Sur la page Paramètres SNMP, sélectionnez *Activer SNMP V1/V2*, puis fournissez une chaîne de communauté en lecture seule et une chaîne de communauté en lecture-écriture.
+
La chaîne de communauté en lecture seule est comme un ID utilisateur ou un mot de passe. Vous devez modifier cette valeur pour empêcher les intrus d'obtenir des informations sur la configuration de votre réseau. La chaîne de communauté lecture-écriture protège le périphérique contre les modifications non autorisées.

. Vous pouvez également sélectionner *Activer le recouvrement* et saisir les informations requises.
+

IMPORTANT: Entrez l'adresse IP de destination pour chaque interruption SNMP utilisant une adresse IP. Les noms de domaine complets ne sont pas pris en charge.

+
Activez les traps si vous souhaitez que le dispositif de Services envoie des notifications immédiates à une console SNMP lorsqu'il est dans un état inhabituel. Les pièges peuvent indiquer des conditions de liaison vers le haut/bas, des températures dépassant certains seuils ou un trafic élevé.

. Vous pouvez également cliquer sur *Envoyer piège de test* pour tester vos paramètres.
. Si les paramètres sont corrects, cliquez sur *Enregistrer*.

