---
permalink: sg100-1000/shut-down-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg1000, SG100, power off, turn off, shut off, shutdown, shut down, 
summary: 'Arrêtez l"appareil de services pour effectuer la maintenance du matériel.' 
---
= Arrêtez l'appliance de services
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrêtez l'appareil de services pour effectuer la maintenance du matériel.

.Ce dont vous avez besoin, 8217;ll
* Vous avez xref:locating-controller-in-data-center.adoc[l'appareil est situé physiquement].
* L'appareil a été xref:placing-appliance-into-maintenance-mode.adoc[passe en mode maintenance].


Pour éviter toute interruption de service, arrêtez l'appliance de services pendant une fenêtre de maintenance planifiée en cas d'interruption de service.

.Étapes
. Lorsque l'appareil a été placé en mode de maintenance, éteignez-le :
+

CAUTION: Vous devez effectuer un arrêt contrôlé du contrôleur en entrant les commandes spécifiées ci-dessous. L'arrêt de l'appareil à l'aide de l'interrupteur d'alimentation entraînera une perte de données.

+
.. Connectez-vous au nœud de la grille à l'aide de PuTTY ou d'un autre client ssh :
+
... Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour passer à la racine : `su -`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



.. Arrêtez l'appareil de services : +
`*shutdown -h now*`
+
Cette commande peut prendre jusqu'à 10 minutes.



. Utilisez l'une des méthodes suivantes pour vérifier que l'appareil est hors tension :
+
** Vérifiez que le voyant d'alimentation situé à l'avant de l'appareil est éteint.
** Consultez la page Power Control de l'interface BMC pour vérifier que l'appliance est éteinte.



