---
permalink: swift/get-container-consistency-request.html 
sidebar: sidebar 
keywords: get container consistency request 
summary: Le niveau de cohérence assure une reprise entre la disponibilité des objets et la cohérence de ces objets sur différents sites et nœuds de stockage. La demande DE cohérence DU conteneur GET vous permet de déterminer le niveau de cohérence appliqué à un conteneur particulier. 
---
= DEMANDE DE cohérence du conteneur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le niveau de cohérence assure une reprise entre la disponibilité des objets et la cohérence de ces objets sur différents sites et nœuds de stockage. La demande DE cohérence DU conteneur GET vous permet de déterminer le niveau de cohérence appliqué à un conteneur particulier.



== Demande

|===
| En-tête HTTP de demande | Description 


 a| 
`X-Auth-Token`
 a| 
Spécifie le jeton d'authentification Swift pour le compte à utiliser pour la demande.



 a| 
`x-ntap-sg-consistency`
 a| 
Spécifie le type de demande, où `true` = COHÉRENCE GARANTIE entre les conteneurs, et `false` = CONTENEUR GET.



 a| 
`Host`
 a| 
Nom d'hôte auquel la demande est dirigée.

|===


== Exemple de demande

[listing]
----
GET /v1/28544923908243208806/Swift container
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: true
Host: test.com
----


== Réponse

|===
| En-tête HTTP de réponse | Description 


 a| 
`Date`
 a| 
La date et l'heure de la réponse.



 a| 
`Connection`
 a| 
Indique si la connexion au serveur est ouverte ou fermée.



 a| 
`X-Trans-Id`
 a| 
Identifiant de transaction unique pour la demande.



 a| 
`Content-Length`
 a| 
Longueur du corps de réponse.



 a| 
`x-ntap-sg-consistency`
 a| 
Niveau de contrôle de cohérence appliqué au conteneur. Les valeurs suivantes sont prises en charge :

* *Tous* : tous les nœuds reçoivent les données immédiatement ou la demande échouera.
* *Forte-global*: Garantit la cohérence lecture-après-écriture pour toutes les demandes client sur tous les sites.
* *Site fort* : garantit la cohérence de lecture après écriture pour toutes les demandes de clients au sein d'un site.
* *Lecture-après-nouvelle-écriture* : offre une cohérence lecture-après-écriture pour les nouveaux objets et une cohérence éventuelle pour les mises à jour d'objets. Offre une haute disponibilité et une protection des données garanties.
+
*Remarque* : si votre application utilise des demandes HEAD sur des objets qui n'existent pas, vous pouvez recevoir un nombre élevé de 500 erreurs de serveur interne si un ou plusieurs nœuds de stockage ne sont pas disponibles. Pour éviter ces erreurs, utilisez le niveau « disponible ».

* *Disponible* (cohérence éventuelle pour les opérations DE TÊTE) : se comporte de la même façon que le niveau de cohérence "entre les nouvelles écritures", mais ne fournit qu'une cohérence éventuelle pour les opérations DE TÊTE. Niveaux de disponibilité supérieurs à ceux de la « nouvelle écriture » en cas d'indisponibilité des nœuds de stockage


|===


== Exemple de réponse

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
x-ntap-sg-consistency: strong-site
----
.Informations associées
xref:../tenant/index.adoc[Utilisez le compte du locataire]
