---
permalink: network/appliance-nodes.html 
sidebar: sidebar 
keywords: networking for appliance, port bond mode 
summary: Vous pouvez configurer les ports réseau sur les appliances StorageGRID de sorte à utiliser les modes de liaison de ports qui répondent à vos exigences en matière de débit, de redondance et de basculement. 
---
= Nœuds d'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les ports réseau sur les appliances StorageGRID de sorte à utiliser les modes de liaison de ports qui répondent à vos exigences en matière de débit, de redondance et de basculement.

Les ports 10/25 GbE des appliances StorageGRID peuvent être configurés en mode de liaison fixe ou agrégée pour les connexions au réseau Grid et au réseau client.

Les ports réseau d'administration 1 GbE peuvent être configurés en mode indépendant ou en mode sauvegarde active pour les connexions au réseau d'administration.

Consultez les informations sur les modes de liaison des ports dans les instructions d'installation et de maintenance de votre appareil :

* xref:../sg100-1000/index.adoc[Appareils de services SG100 et SG1000]
* xref:../sg6000/index.adoc[Dispositifs de stockage SG6000]
* xref:../sg5700/index.adoc[Appliances de stockage SG5700]
* xref:../sg5600/index.adoc[Appliances de stockage SG5600]

