---
permalink: sg5600/gathering-installation-information-sg5600.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation 
summary: 'Lors de l"installation et de la configuration de l"appliance StorageGRID, vous devez prendre des décisions et collecter des informations sur les ports de commutation Ethernet, les adresses IP et les modes de liaison réseau et de port.' 
---
= Collecte des informations sur l'installation (SG5600)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de l'installation et de la configuration de l'appliance StorageGRID, vous devez prendre des décisions et collecter des informations sur les ports de commutation Ethernet, les adresses IP et les modes de liaison réseau et de port.

Vous pouvez utiliser les tableaux suivants pour enregistrer des informations sur chaque réseau connecté à l'appliance. Ces valeurs sont nécessaires pour installer et configurer le matériel.



== Informations nécessaires pour connecter le contrôleur E2700 à SANtricity Storage Manager

Vous devez connecter le contrôleur E2700 au réseau de gestion que vous utiliserez pour SANtricity Storage Manager.

|===
| Informations nécessaires | Votre valeur 


 a| 
Port de commutateur Ethernet vous connectez au port de gestion 1
 a| 



 a| 
Adresse MAC pour le port de gestion 1 (imprimée sur une étiquette près du port P1)
 a| 



 a| 
Adresse IP attribuée par DHCP pour le port de gestion 1, si disponible après la mise sous tension

*Remarque :* si le réseau auquel vous vous connectez au contrôleur E2700 comporte un serveur DHCP, l'administrateur réseau peut utiliser l'adresse MAC pour déterminer l'adresse IP attribuée par le serveur DHCP.
 a| 



 a| 
Vitesse et mode duplex

*Remarque :* vous devez vous assurer que le commutateur Ethernet du réseau de gestion SANtricity Storage Manager est défini sur négociation automatique.
 a| 
Doit être :

* Négociation automatique (par défaut)




 a| 
Format d'adresse IP
 a| 
Choisir une option :

* IPv4
* IPv6




 a| 
Adresse IP statique que vous prévoyez d'utiliser pour l'appliance sur le réseau de gestion
 a| 
Pour IPv4 :

* Adresse IPv4 :
* Masque de sous-réseau :
* Passerelle :


Pour IPv6 :

* Adresse IPv6 :
* Adresse IP routable :
* Adresse IP du routeur du contrôleur E2700 :


|===


== Informations nécessaires pour connecter le contrôleur E5600SG au réseau Admin

Le réseau d'administration pour StorageGRID est un réseau facultatif, utilisé pour l'administration et la maintenance du système. L'appliance se connecte au réseau d'administration via les ports de gestion 1 GbE du contrôleur E5600SG.

|===
| Informations nécessaires | Votre valeur 


 a| 
Réseau admin activé
 a| 
Choisir une option :

* Non
* Oui (par défaut)




 a| 
Mode de liaison réseau
 a| 
Choisir une option :

* Indépendant
* Sauvegarde active-Backup




 a| 
Port switch pour le port de gestion 1 (P1)
 a| 



 a| 
Port de commutateur pour le port de gestion 2 (P2 ; mode de liaison réseau Active-Backup uniquement)
 a| 



 a| 
Adresse MAC pour le port de gestion 1 (imprimée sur une étiquette près du port P1)
 a| 



 a| 
Adresse IP attribuée par DHCP pour le port de gestion 1, si disponible après la mise sous tension

*Remarque :* si le réseau d'administration comprend un serveur DHCP, le contrôleur E5600SG affiche l'adresse IP attribuée par DHCP sur son affichage à sept segments après son démarrage. Vous pouvez également déterminer l'adresse IP attribuée par DHCP en utilisant l'adresse MAC pour rechercher l'adresse IP attribuée.
 a| 
* Adresse IPv4 (CIDR) :
* Passerelle :




 a| 
Adresse IP statique que vous envisagez d'utiliser pour le nœud de stockage de l'appliance sur le réseau d'administration

*Remarque :* si votre réseau n'a pas de passerelle, spécifiez la même adresse IPv4 statique pour la passerelle.
 a| 
* Adresse IPv4 (CIDR) :
* Passerelle :




 a| 
Sous-réseaux du réseau d'administration (CIDR)
 a| 

|===


== Informations nécessaires pour la connexion et la configuration des ports 10 GbE sur le contrôleur E5600SG

Les quatre ports 10 GbE du contrôleur E5600SG se connectent au réseau StorageGRID Grid et au réseau client.


NOTE: Pour plus d'informations sur les options de ces ports, reportez-vous à la section « connexions de ports 10 GbE pour le contrôleur E5600SG ».

|===
| Informations nécessaires | Votre valeur 


 a| 
Mode de liaison du port
 a| 
Choisir une option :

* Fixe (par défaut)
* Agrégat




 a| 
Port de commutation pour le port 1 (réseau client pour mode fixe)
 a| 



 a| 
Port de commutation pour le port 2 (réseau grille pour mode fixe)
 a| 



 a| 
Port de commutation pour le port 3 (réseau client pour mode fixe)
 a| 



 a| 
Port de commutation pour le port 4 (réseau Grid pour mode fixe)
 a| 

|===


== Informations nécessaires pour connecter le contrôleur E5600SG au réseau Grid

Le réseau Grid Network pour StorageGRID est un réseau requis, utilisé pour l'ensemble du trafic StorageGRID interne. L'appliance se connecte au réseau Grid à l'aide des ports 10 GbE du contrôleur E5600SG.


NOTE: Pour plus d'informations sur les options de ces ports, reportez-vous à la section « connexions de ports 10 GbE pour le contrôleur E5600SG ».

|===
| Informations nécessaires | Votre valeur 


 a| 
Mode de liaison réseau
 a| 
Choisir une option :

* Sauvegarde active/active (par défaut)
* LACP (802.3ad)




 a| 
Balisage VLAN activé
 a| 
Choisir une option :

* Non (par défaut)
* Oui.




 a| 
Balise VLAN (si le marquage VLAN est activé)
 a| 
Entrez une valeur comprise entre 0 et 4095 :



 a| 
Adresse IP attribuée par DHCP pour le réseau Grid, si disponible après la mise sous tension

*Remarque :* si le réseau Grid comprend un serveur DHCP, le contrôleur E5600SG affiche l'adresse IP attribuée par DHCP pour le réseau Grid sur son affichage à sept segments après son démarrage.
 a| 
* Adresse IPv4 (CIDR) :
* Passerelle :




 a| 
Adresse IP statique que vous prévoyez d'utiliser pour le noeud de stockage de l'appliance sur le réseau Grid

*Remarque :* si votre réseau n'a pas de passerelle, spécifiez la même adresse IPv4 statique pour la passerelle.
 a| 
* Adresse IPv4 (CIDR) :
* Passerelle :




 a| 
Sous-réseaux du réseau de grille (CIDR)

*Remarque :* si le réseau client n'est pas activé, la route par défaut du contrôleur utilisera la passerelle indiquée ici.
 a| 

|===


== Informations nécessaires pour connecter le contrôleur E5600SG au réseau client

Le réseau client pour StorageGRID est un réseau facultatif, utilisé pour fournir un accès au protocole client à la grille. L'appliance se connecte au réseau client à l'aide des ports 10 GbE du contrôleur E5600SG.


NOTE: Pour plus d'informations sur les options de ces ports, reportez-vous à la section « connexions de ports 10 GbE pour le contrôleur E5600SG ».

|===
| Informations nécessaires | Votre valeur 


 a| 
Réseau client activé
 a| 
Choisir une option :

* Non (par défaut)
* Oui.




 a| 
Mode de liaison réseau
 a| 
Choisir une option :

* Sauvegarde active/active (par défaut)
* LACP (802.3ad)




 a| 
Balisage VLAN activé
 a| 
Choisir une option :

* Non (par défaut)
* Oui.




 a| 
Balise VLAN (si le marquage VLAN est activé)
 a| 
Entrez une valeur comprise entre 0 et 4095 :



 a| 
Adresse IP attribuée par DHCP pour le réseau client, si disponible après la mise sous tension
 a| 
* Adresse IPv4 (CIDR) :
* Passerelle :




 a| 
Adresse IP statique que vous prévoyez d'utiliser pour le noeud de stockage de l'appliance sur le réseau client

*Remarque :* si le réseau client est activé, la route par défaut du contrôleur utilisera la passerelle indiquée ici.
 a| 
* Adresse IPv4 (CIDR) :
* Passerelle :


|===
xref:reviewing-appliance-network-connections-sg5600.adoc[Examiner les connexions réseau de l'appliance (SG5600)]

xref:configuring-hardware.adoc[Configuration matérielle (SG5600)]

xref:port-bond-modes-for-e5600sg-controller-ports.adoc[Modes de liaison des ports pour les ports du contrôleur E5600SG]
