---
permalink: sg5600/installation-and-deployment-overview.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, Installation, deployment, Install, deploy, Installing, deploying 
summary: 'Vous pouvez installer une ou plusieurs appliances StorageGRID lors du premier déploiement de StorageGRID, ou ajouter ultérieurement des nœuds de stockage dans le cadre d"une extension. Vous devrez peut-être également installer un nœud de stockage d"appliance dans le cadre d"une opération de restauration.' 
---
= Présentation de l'installation et du déploiement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer une ou plusieurs appliances StorageGRID lors du premier déploiement de StorageGRID, ou ajouter ultérieurement des nœuds de stockage dans le cadre d'une extension. Vous devrez peut-être également installer un nœud de stockage d'appliance dans le cadre d'une opération de restauration.

L'ajout d'une appliance de stockage StorageGRID à un système StorageGRID comprend quatre étapes principales :

. Préparation de l'installation :
+
** Préparation du site d'installation
** Déballage des boîtes et vérification du contenu
** Obtenir des équipements et des outils supplémentaires
** Collecte des adresses IP et des informations réseau
** Facultatif : configuration d'un serveur de gestion des clés externe (KMS) si vous prévoyez de crypter toutes les données de l'appliance. Pour plus d'informations sur la gestion externe des clés, reportez-vous aux instructions d'administration de StorageGRID.


. Installation du matériel :
+
** Enregistrement du matériel
** Installation de l'appliance dans une armoire ou un rack
** Installation des disques (SG5660 uniquement)
** Câblage de l'appareil
** Branchement des câbles d'alimentation et alimentation électrique
** Affichage des codes d'état de démarrage


. Configuration du matériel :
+
** Accès à SANtricity Storage Manager, définition d'une adresse IP statique pour le port de gestion 1 sur le contrôleur E2700 et configuration des paramètres SANtricity Storage Manager
** Accès au programme d'installation de l'appliance StorageGRID et configuration des paramètres de liaison et de réseau IP requis pour la connexion aux réseaux StorageGRID
** Facultatif : activation du chiffrement de nœud si vous prévoyez d'utiliser un KMS externe pour chiffrer les données de l'appliance.
** Facultatif : modification du mode RAID.


. Déploiement de l'appliance en tant que nœud de stockage :


|===
| Tâche | Reportez-vous à la section 


 a| 
Déploiement d'une appliance de nœud de stockage dans un nouveau système StorageGRID
 a| 
xref:deploying-appliance-storage-node.adoc[Déployez le nœud de stockage de l'appliance]



 a| 
Ajout d'un nœud de stockage d'appliance à un système StorageGRID existant
 a| 
Instructions d'extension d'un système StorageGRID



 a| 
Déploiement d'un nœud de stockage d'appliance dans le cadre d'une opération de restauration du nœud de stockage
 a| 
Instructions de récupération et de maintenance

|===
.Informations associées
xref:preparing-for-installation.adoc[Préparation à l'installation (SG5600)]

xref:installing-hardware.adoc[Installation du matériel (SG5600)]

xref:configuring-hardware.adoc[Configuration matérielle (SG5600)]

xref:../expand/index.adoc[Développez votre grille]

xref:../maintain/index.adoc[Récupérer et entretenir]

xref:../admin/index.adoc[Administrer StorageGRID]
