---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: 'Si vous utilisez un locataire S3, vous pouvez utiliser le gestionnaire des locataires ou l"API de gestion des locataires pour modifier le contrôle de cohérence pour les opérations effectuées sur les objets dans des compartiments S3.' 
---
= Modifiez le niveau de cohérence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez un locataire S3, vous pouvez utiliser le gestionnaire des locataires ou l'API de gestion des locataires pour modifier le contrôle de cohérence pour les opérations effectuées sur les objets dans des compartiments S3.

.Ce dont vous avez besoin, 8217;ll
* Vous devez être connecté au Gestionnaire de locataires à l'aide d'un xref:../admin/web-browser-requirements.adoc[navigateur web pris en charge].
* Vous devez appartenir à un groupe d'utilisateurs possédant l'autorisation gérer toutes les rubriques ou accès racine. Ces autorisations remplacent les paramètres d'autorisations des stratégies de groupes ou de compartiments. Voir xref:tenant-management-permissions.adoc[Autorisations de gestion des locataires].


Le niveau de cohérence assure une reprise entre la disponibilité des objets et la cohérence de ces objets sur différents sites et nœuds de stockage. En général, vous devez utiliser le niveau de cohérence *Read-After-New-write* pour vos compartiments. Si le niveau de cohérence *Read-After-New-write* ne répond pas aux exigences de l'application client, vous pouvez modifier le niveau de cohérence en définissant le niveau de cohérence du compartiment ou en utilisant le `Consistency-Control` en-tête. Le `Consistency-Control` le cueilleur remplace le niveau de cohérence du godet.


NOTE: Lorsque vous modifiez le niveau de cohérence d'un compartiment, seuls les objets ingérées après la modification sont garantis pour satisfaire le niveau révisé.

.Étapes
. Sélectionnez *STOCKAGE (S3)* *seaux*.
. Sélectionnez le nom du compartiment dans la liste.
+
La page des détails du compartiment s'affiche.

. Sélectionnez *Options de rubrique* *niveau de cohérence*.
. Sélectionnez un niveau de cohérence pour les opérations effectuées sur les objets de ce compartiment.
+
[cols="1a,3a"]
|===
| Niveau de cohérence | Description 


 a| 
Tout
 a| 
Tous les nœuds reçoivent les données immédiatement, sinon la requête échoue.



 a| 
Forte croissance mondiale
 a| 
Garantit une cohérence de lecture après écriture pour toutes les demandes client sur tous les sites.



 a| 
Site fort
 a| 
Garantit la cohérence de lecture après écriture pour toutes les demandes client dans un site.



 a| 
Lecture après nouvelle écriture (par défaut)
 a| 
Assure la cohérence de lecture après écriture pour les nouveaux objets et la cohérence des mises à jour d'objets. Offre une haute disponibilité et une protection des données garanties. Le correspondance le plus étroite avec les garanties de cohérence Amazon S3.

*Remarque :* si votre application tente D'EFFECTUER DES opérations SUR des clés qui n'existent pas, définissez le niveau de cohérence sur *disponible*, à moins que vous n'ayez besoin des garanties de cohérence Amazon S3. Sinon, un nombre élevé de 500 erreurs de serveur interne peuvent se produire si un ou plusieurs nœuds de stockage ne sont pas disponibles.



 a| 
Disponible (cohérence possible pour LA TÊTE ou LES opérations)
 a| 
Se comporte de la même manière que le niveau de cohérence *Read-After-New-write*, mais fournit une cohérence éventuelle pour les opérations HEAD et GET. Offre une disponibilité supérieure pour LA TÊTE et DES opérations SUPÉRIEURES à *lecture-après-nouvelle-écriture* si les nœuds de stockage ne sont pas disponibles. Elle diffère des garanties de cohérence Amazon S3 pour LA TÊTE et LES opérations GET.

|===
. Sélectionnez *Enregistrer les modifications*.

