---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: 'Si vous utilisez un locataire S3, vous pouvez utiliser le gestionnaire des locataires ou l"API de gestion des locataires pour modifier le contrôle de cohérence pour les opérations effectuées sur les objets dans des compartiments S3.' 
---
= Modifiez le niveau de cohérence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez un locataire S3, vous pouvez utiliser le gestionnaire des locataires ou l'API de gestion des locataires pour modifier le contrôle de cohérence pour les opérations effectuées sur les objets dans des compartiments S3.

.Ce dont vous avez besoin
* Vous devez être connecté au Gestionnaire de locataires à l'aide d'un xref:../admin/web-browser-requirements.adoc[navigateur web pris en charge].
* Vous devez appartenir à un groupe d'utilisateurs possédant l'autorisation gérer toutes les rubriques ou accès racine. Ces autorisations remplacent les paramètres d'autorisations des stratégies de groupes ou de compartiments. Voir xref:tenant-management-permissions.adoc[Autorisations de gestion des locataires].


.Description de la tâche
Le niveau de cohérence assure un équilibre entre la disponibilité des objets et la cohérence de ces objets entre plusieurs nœuds de stockage et sites. En général, vous devez utiliser le niveau de cohérence *Read-After-New-write* pour vos compartiments.

Si le niveau de cohérence *Read-After-New-write* ne répond pas aux exigences de l'application client, vous pouvez modifier le niveau de cohérence en définissant le niveau de cohérence du compartiment ou en utilisant le `Consistency-Control` en-tête. Le `Consistency-Control` le cueilleur remplace le niveau de cohérence du godet.


NOTE: Lorsque vous modifiez le niveau de cohérence d'un compartiment, seuls les objets ingérées après la modification sont garantis pour satisfaire le niveau révisé.

.Étapes
. Sélectionnez *STOCKAGE (S3)* *seaux*.
. Sélectionnez le nom du compartiment dans la liste.
+
La page des détails du compartiment s'affiche.

. Sélectionnez *Options de rubrique* *niveau de cohérence*.
. Sélectionnez un niveau de cohérence pour les opérations effectuées sur les objets de ce compartiment.
+
** *Tous* : fournit le plus haut niveau de cohérence. Tous les nœuds reçoivent les données immédiatement, sinon la requête échoue.
** *Strong-global* : garantit la cohérence lecture après écriture pour toutes les demandes client sur tous les sites.
** *Strong-site* : garantit la cohérence lecture après écriture pour toutes les demandes client au sein d'un site.
** *Read-After-New-write* (par défaut) : fournit une cohérence lecture-après-écriture pour les nouveaux objets et une cohérence éventuelle pour les mises à jour d'objets. Offre une haute disponibilité et une protection des données garanties. Recommandé dans la plupart des cas.
** *Disponible* : assure la cohérence finale pour les nouveaux objets et les mises à jour d'objets. Pour les compartiments S3, utilisez uniquement si nécessaire (par exemple, pour un compartiment qui contient des valeurs de journal rarement lues ou pour les opérations HEAD ou GET sur des clés qui n'existent pas). Non pris en charge pour les compartiments FabricPool S3.


. Sélectionnez *Enregistrer les modifications*.

