---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: how to duplicate tenant group 
summary: Vous pouvez créer de nouveaux groupes plus rapidement en dupliquant un groupe existant. 
---
= Dupliquer le groupe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer de nouveaux groupes plus rapidement en dupliquant un groupe existant.

.Ce dont vous avez besoin
* Vous devez être connecté au Gestionnaire de locataires à l'aide d'un xref:../admin/web-browser-requirements.adoc[navigateur web pris en charge].
* Vous devez appartenir à un groupe d'utilisateurs qui dispose de l'autorisation accès racine. Voir xref:tenant-management-permissions.adoc[Autorisations de gestion des locataires].


.Étapes
. Sélectionnez *ACCESS MANAGEMENT* *Groups*.
. Cochez la case correspondant au groupe que vous souhaitez dupliquer.
. Sélectionnez *Dupliquer le groupe*. Pour plus d'informations sur la création d'un groupe, reportez-vous aux instructions de création de groupes pour xref:creating-groups-for-s3-tenant.adoc[Un locataire S3] ou pour xref:creating-groups-for-swift-tenant.adoc[Un locataire Swift].
. Sélectionnez l'onglet *Groupe local* pour créer un groupe local ou sélectionnez l'onglet *Groupe fédéré* pour importer un groupe à partir du référentiel d'identité configuré précédemment.
+
Si l'authentification unique (SSO) est activée pour votre système StorageGRID, les utilisateurs appartenant à des groupes locaux ne pourront pas se connecter au Gestionnaire de locataires, bien qu'ils puissent utiliser les applications client pour gérer les ressources du locataire, xref:tenant-management-permissions.adoc[en fonction des autorisations de groupe].

. Entrez le nom du groupe.
+
** *Groupe local* : saisissez à la fois un nom d'affichage et un nom unique. Vous pouvez modifier le nom d'affichage ultérieurement.
** *Groupe fédéré* : saisissez le nom unique. Pour Active Directory, le nom unique est le nom associé à l' `sAMAccountName` attribut. Pour OpenLDAP, le nom unique est le nom associé à `uid` attribut.


. Sélectionnez *Continuer*.
. Si nécessaire, modifiez les autorisations pour ce groupe.
. Sélectionnez *Continuer*.
. Si nécessaire, si vous copiez un groupe pour un locataire S3, vous pouvez sélectionner une autre stratégie à partir des boutons d'option *Ajouter une stratégie S3*. Si vous avez sélectionné une règle personnalisée, mettez à jour la chaîne JSON si nécessaire.
. Sélectionnez *Créer groupe*.

