---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Un compte de locataire vous permet d"utiliser l"API REST S3 (simple Storage Service) ou l"API REST Swift pour stocker et récupérer des objets dans un système StorageGRID.' 
---
= Utilisez un compte de locataire : présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un compte de locataire vous permet d'utiliser l'API REST S3 (simple Storage Service) ou l'API REST Swift pour stocker et récupérer des objets dans un système StorageGRID.



== Qu'est-ce qu'un compte de locataire ?

Chaque compte de locataire possède ses propres groupes, utilisateurs, compartiments S3, conteneurs Swift et objets fédérés.

Il est possible d'utiliser des comptes de tenant pour isoler les objets stockés par différentes entités. Par exemple, vous pouvez utiliser plusieurs comptes locataires pour l'une de ces utilisations :

* *Utilisation en entreprise :* si le système StorageGRID est utilisé au sein d'une entreprise, le stockage objet de la grille peut être séparé par les différents services de l'organisation. Par exemple, il peut y avoir des comptes de tenant pour le service Marketing, le service Customer support, le service des ressources humaines, etc.
+

NOTE: Si vous utilisez le protocole client S3, vous pouvez également utiliser des compartiments S3 et des règles de compartiment pour isoler les objets entre les différents départements d'une entreprise. Il n'est pas nécessaire de créer des comptes de tenant distincts. Voir la xref:../s3/index.adoc[Instructions d'implémentation des applications client S3].

* *Cas d'utilisation du fournisseur de services :* si le système StorageGRID est utilisé par un fournisseur de services, le stockage objet de la grille peut être séparé par les différentes entités qui louent le stockage. Il peut s'agir, par exemple, de comptes de locataires pour la société A, la société B, la société C, etc.




== Comment créer un compte de locataire

Les comptes de locataire sont créés par un xref:../admin/managing-tenants.adoc[Administrateur du grid StorageGRID utilisant le gestionnaire de grille]. Lors de la création d'un compte de locataire, l'administrateur du grid spécifie les informations suivantes :

* Nom d'affichage du locataire (l'ID de compte du locataire est attribué automatiquement et ne peut pas être modifié).
* Si le compte de locataire utilise S3 ou Swift.
* Pour les comptes de locataire S3 : si le compte de locataire est autorisé à utiliser des services de plateforme. Si l'utilisation des services de plateforme est autorisée, la grille doit être configurée pour prendre en charge leur utilisation.
* Éventuellement, un quota de stockage pour le compte du locataire, soit le nombre maximal de gigaoctets, téraoctets ou pétaoctets disponibles pour les objets du locataire. Le quota de stockage d'un locataire représente une quantité logique (taille d'objet), et non une quantité physique (taille sur disque).
* Si la fédération des identités est activée pour le système StorageGRID, quel groupe fédéré a l'autorisation d'accès racine pour configurer le compte de tenant.
* Si l'authentification unique (SSO) n'est pas utilisée pour le système StorageGRID, que le compte de tenant utilise son propre référentiel d'identité ou partage le référentiel d'identité de la grille et le mot de passe initial de l'utilisateur racine local du locataire.


En outre, les administrateurs du grid peuvent activer le paramètre de verrouillage objet S3 pour le système StorageGRID si les comptes de locataires S3 doivent être conformes aux exigences réglementaires. Lorsque le verrouillage des objets S3 est activé, tous les comptes de locataires S3 peuvent créer et gérer des compartiments conformes.



=== Configurez les locataires S3

Après un xref:../admin/creating-tenant-account.adoc[Le compte de locataire S3 est créé], Vous pouvez accéder au Gestionnaire de tenant pour effectuer des tâches telles que :

* Configuration de la fédération des identités (sauf si le référentiel d'identité est partagé avec la grille) ou création de groupes et d'utilisateurs locaux
* Gestion des clés d'accès S3
* Création et gestion des compartiments S3, notamment des compartiments conformes
* Utilisation des services de plate-forme (si activé)
* Contrôle de l'utilisation du stockage



IMPORTANT: Vous devez avoir la possibilité de créer et de gérer des compartiments S3 avec le Gestionnaire des locataires xref:../s3/index.adoc[Les clés d'accès S3 et utilisent l'API REST S3 pour ingérer et gérer les objets].



=== Configurez les locataires Swift

Après un xref:../admin/creating-tenant-account.adoc[Le compte de locataire Swift est créé], Vous pouvez accéder au Gestionnaire de tenant pour effectuer des tâches telles que :

* Configuration de la fédération des identités (sauf si le référentiel d'identité est partagé avec la grille) et création de groupes et d'utilisateurs locaux
* Contrôle de l'utilisation du stockage



IMPORTANT: Les utilisateurs Swift doivent disposer de l'autorisation d'accès racine pour accéder au gestionnaire de locataires. Toutefois, l'autorisation accès racine ne permet pas aux utilisateurs de s'authentifier dans le système xref:../swift/index.adoc[API REST Swift] pour créer des conteneurs et ingérer des objets. Les utilisateurs doivent disposer de l'autorisation Administrateur Swift pour s'authentifier dans l'API REST de Swift.



== Utilisez le Gestionnaire de locataires

Le gestionnaire de locataires permet de gérer tous les aspects d'un compte de locataire StorageGRID.

Vous pouvez utiliser le gestionnaire des locataires pour surveiller l'utilisation du stockage d'un compte de locataire et gérer les utilisateurs avec une fédération des identités ou en créant des groupes et des utilisateurs locaux. Pour les comptes locataires S3, vous pouvez également gérer des clés S3, gérer des compartiments S3 et configurer les services de plateforme.
