---
permalink: tenant/understanding-notifications-for-buckets.html 
sidebar: sidebar 
keywords: s3 bucket event notification, sequencer key 
summary: 'Vous pouvez activer la notification d"événements pour un compartiment S3 si vous souhaitez que StorageGRID envoie des notifications sur des événements spécifiés vers un service Amazon simple notification Service \(SNS\) de destination.' 
---
= Description des notifications pour les compartiments
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer la notification des événements pour un compartiment S3 si vous souhaitez que StorageGRID envoie des notifications sur les événements spécifiés à un service Amazon simple notification Service (SNS) de destination.

C'est possible xref:configuring-event-notifications.adoc[configurer les notifications d'événements] En associant XML de configuration de notification à un compartiment source. Le XML de configuration de notification respecte les conventions S3 pour la configuration des notifications de compartiment, avec la rubrique SNS de destination spécifiée comme URN d'un terminal.

Les notifications d'événements sont créées au niveau du compartiment source, comme indiqué dans la configuration de la notification, et sont envoyées vers le compartiment de destination. Si un événement associé à un objet réussit, une notification concernant cet événement est créée et mise en file d'attente pour la livraison.

Notre approche unique et notre ordre des notifications ne sont pas garantis. Plusieurs notifications d'événement peuvent être envoyées vers la destination après les opérations effectuées pour garantir la réussite de la livraison. La livraison étant asynchrone, l'ordre dans le temps des notifications au niveau de la destination n'est pas garanti correspondant à l'ordre des événements dans le compartiment source, en particulier pour les opérations provenant de différents sites StorageGRID. Vous pouvez utiliser le `sequencer` Key dans le message d'événement pour déterminer l'ordre des événements pour un objet particulier, tel que décrit dans la documentation Amazon S3.



== Notifications et messages pris en charge

La notification d'événements StorageGRID suit l'API Amazon S3 avec les limites suivantes :

* Vous ne pouvez pas configurer une notification pour les types d'événements suivants. Ces types d'événements sont *non* pris en charge.
+
** `s3:ReducedRedundancyLostObject`
** `s3:ObjectRestore:Completed`


* Les notifications d'événements envoyées par StorageGRID utilisent le format JSON standard, sauf qu'elles n'incluent pas certaines clés et utilisent des valeurs spécifiques pour les autres, comme illustré dans le tableau :


[cols="1a,2a"]
|===
| Nom de la clé | Valeur ajoutée de StorageGRID 


 a| 
Source d'événements
 a| 
`sgws:s3`



 a| 
Région de l'awsRegion
 a| 
non inclus



 a| 
x-amz-id-2
 a| 
non inclus



 a| 
arn
 a| 
`urn:sgws:s3:::bucket_name`

|===