---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to plan before installation 
summary: Avant de déployer des nœuds grid et de configurer la grille de StorageGRID, vous devez connaître les étapes et les conditions requises pour terminer la procédure. 
---
= Avant d'installer (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer des nœuds grid et de configurer la grille de StorageGRID, vous devez connaître les étapes et les conditions requises pour terminer la procédure.

Les procédures de déploiement et de configuration de StorageGRID supposent que vous connaissez bien l'architecture et les fonctionnalités opérationnelles du système StorageGRID.

Vous pouvez déployer un ou plusieurs sites à la fois. Toutefois, tous les sites doivent respecter le minimum requis : disposer d'au moins trois nœuds de stockage.


IMPORTANT: StorageGRID ne prend pas en charge l'utilisation des SAN virtuels, car la protection des disques sous-jacents n'est pas un RAID matériel.

Avant de démarrer la procédure de déploiement de nœuds et de configuration grid, vous devez :

* Planification du déploiement StorageGRID
* Installez, connectez et configurez tout le matériel requis, y compris les appliances StorageGRID, selon les spécifications.
+

NOTE: Des instructions d'installation et d'intégration spécifiques au matériel ne sont pas incluses dans la procédure d'installation de StorageGRID. Pour savoir comment installer des appliances StorageGRID, consultez les instructions d'installation et de maintenance de votre appareil.

* Prenez connaissance du xref:../network/index.adoc[options réseau disponibles et mise en œuvre de chaque option réseau sur les nœuds grid].
* Rassemblez toutes les informations de réseautage à l'avance. Sauf si vous utilisez DHCP, rassemblez les adresses IP à attribuer à chaque nœud de la grille ainsi que les adresses IP des serveurs DNS (Domain Name System) et NTP (Network Time Protocol) qui seront utilisés.
* Choisissez les outils de déploiement et de configuration que vous souhaitez utiliser.


xref:../sg100-1000/index.adoc[Appareils de services SG100 et SG1000]

xref:../sg6000/index.adoc[Dispositifs de stockage SG6000]

xref:../sg5700/index.adoc[Appliances de stockage SG5700]

xref:../sg5600/index.adoc[Appliances de stockage SG5600]
