---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: 'En cas de problème lors de l"installation de votre système StorageGRID, vous pouvez accéder aux fichiers journaux d"installation.' 
---
= Résoudre les problèmes d'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En cas de problème lors de l'installation de votre système StorageGRID, vous pouvez accéder aux fichiers journaux d'installation.

Voici les principaux fichiers journaux d'installation dont le support technique peut avoir besoin pour résoudre les problèmes.

* `/var/local/log/install.log` (disponible sur tous les nœuds de la grille)
* `/var/local/log/gdu-server.log` (Trouvé sur le nœud d'administration principal)


Pour savoir comment accéder aux fichiers journaux, reportez-vous à la section xref:../monitor/index.adoc[Instructions de surveillance et de dépannage de StorageGRID]. Pour obtenir de l'aide sur le dépannage des problèmes d'installation de l'appareil, consultez les instructions d'installation et de maintenance de vos appareils. Si vous avez besoin d'aide supplémentaire, contactez le support technique.

xref:../sg100-1000/index.adoc[Appareils de services SG100 et SG1000]

xref:../sg6000/index.adoc[Dispositifs de stockage SG6000]

xref:../sg5700/index.adoc[Appliances de stockage SG5700]

xref:../sg5600/index.adoc[Appliances de stockage SG5600]

https://["Support NetApp"^]



== La réservation de ressources de machine virtuelle nécessite un ajustement

Les fichiers OVF incluent une réservation de ressources conçue pour garantir que chaque nœud de grille dispose de suffisamment de RAM et de CPU pour fonctionner efficacement. Si vous créez des machines virtuelles en déployant ces fichiers OVF sur VMware et que le nombre prédéfini de ressources n'est pas disponible, les machines virtuelles ne démarrent pas.

.Description de la tâche
Si vous êtes certain que l'hôte VM dispose de ressources suffisantes pour chaque nœud de la grille, ajustez manuellement les ressources allouées à chaque machine virtuelle, puis essayez de démarrer les machines virtuelles.

.Étapes
. Dans l'arborescence du client VMware vSphere Hypervisor, sélectionnez la machine virtuelle qui n'a pas démarré.
. Cliquez avec le bouton droit de la souris sur la machine virtuelle et sélectionnez *Modifier les paramètres*.
. Dans la fenêtre Propriétés des machines virtuelles, sélectionnez l'onglet *Ressources*.
. Ajustez les ressources allouées à la machine virtuelle :
+
.. Sélectionnez *CPU*, puis utilisez le curseur réservation pour régler la fréquence réservée à cette machine virtuelle.
.. Sélectionnez *mémoire*, puis utilisez le curseur réservation pour régler le Mo réservé pour cette machine virtuelle.


. Cliquez sur *OK*.
. Répétez cette procédure si nécessaire pour les autres machines virtuelles hébergées sur le même hôte VM.

