---
permalink: admin/administering-storagegrid-system.html 
sidebar: sidebar 
keywords: administration overview 
summary: Suivez ces instructions pour configurer et administrer un système StorageGRID. 
---
= Administration d'un système StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour configurer et administrer un système StorageGRID.

Ces instructions expliquent comment utiliser Grid Manager pour configurer des groupes et des utilisateurs, créer des comptes de locataires pour permettre aux applications client S3 et Swift de stocker et récupérer des objets, configurer et gérer des réseaux StorageGRID, configurer AutoSupport, gérer des paramètres de nœud, etc.

[NOTE]
====
Il a été déplacé les instructions de gestion des objets avec des règles et des règles de gestion du cycle de vie des informations (ILM) versxref:../ilm/index.adoc[Gestion des objets avec ILM].

====
Ces instructions s'adresse au personnel technique qui devra configurer, administrer et prendre en charge un système StorageGRID après son installation.

.Ce dont vous avez besoin
* Vous disposez d'une compréhension générale du système StorageGRID.
* Vous disposez d'une connaissance assez détaillée des shells de commande Linux, de la mise en réseau et de la configuration matérielle du serveur.

