---
permalink: admin/configuring-audit-client-for-nfs.html 
sidebar: sidebar 
keywords: audit client for NFS 
summary: 'Le partage d"audit est automatiquement activé en tant que partage en lecture seule.' 
---
= Configuration du client d'audit pour NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le partage d'audit est automatiquement activé en tant que partage en lecture seule.

.Ce dont vous avez besoin
* Vous avez le `Passwords.txt` Fichier avec le mot de passe root/admin (disponible dans LEDIT paquet).
* Vous avez le `Configuration.txt` Fichier (disponible dans LEDIT paquet).
* Le client d'audit utilise NFS version 3 (NFSv3).


.Description de la tâche
Effectuez cette procédure pour chaque nœud d'administration d'un déploiement StorageGRID à partir duquel vous souhaitez récupérer des messages d'audit.

.Étapes
. Connectez-vous au nœud d'administration principal :
+
.. Saisissez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Vérifiez que tous les services sont en cours d'exécution ou vérifiés. Entrez : `storagegrid-status`
+
Si des services ne sont pas répertoriés comme en cours d'exécution ou vérifiés, résolvez les problèmes avant de continuer.

. Revenez à la ligne de commande. Appuyez sur *Ctrl*+*C*.
. Démarrez l'utilitaire de configuration NFS. Entrez : `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. Ajouter le client d'audit : `add-audit-share`
+
.. Lorsque vous y êtes invité, entrez l'adresse IP ou la plage d'adresses IP du client d'audit pour le partage d'audit : `client_IP_address`
.. Lorsque vous y êtes invité, appuyez sur *entrée*.


. Si plusieurs clients d'audit sont autorisés à accéder au partage d'audit, ajoutez l'adresse IP de l'utilisateur supplémentaire : `add-ip-to-share`
+
.. Entrez le numéro du partage d'audit : `_audit_share_number_`
.. Lorsque vous y êtes invité, entrez l'adresse IP ou la plage d'adresses IP du client d'audit pour le partage d'audit : `_client_IP_address_`
.. Lorsque vous y êtes invité, appuyez sur *entrée*.
+
L'utilitaire de configuration NFS s'affiche.

.. Répétez ces sous-étapes pour chaque client d'audit supplémentaire ayant accès au partage d'audit.


. Vérifiez éventuellement votre configuration.
+
.. Saisissez les informations suivantes : `validate-config`
+
Les services sont vérifiés et affichés.

.. Lorsque vous y êtes invité, appuyez sur *entrée*.
+
L'utilitaire de configuration NFS s'affiche.

.. Fermez l'utilitaire de configuration NFS : `exit`


. Déterminez si vous devez activer des partages d'audit sur d'autres sites.
+
** Si le déploiement de StorageGRID est un site unique, passez à l'étape suivante.
** Si le déploiement de StorageGRID inclut des nœuds d'administration sur d'autres sites, activez ces partages d'audit si nécessaire :
+
... Connectez-vous à distance au nœud d'administration du site :
+
.... Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
.... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.... Entrez la commande suivante pour passer à la racine : `su -`
.... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


... Répétez cette procédure pour configurer les partages d'audit pour chaque nœud d'administration supplémentaire.
... Fermez la connexion du shell sécurisé distant au nœud d'administration distant. Entrez : `exit`




. Déconnectez-vous du shell de commande : `exit`
+
Les clients d'audit NFS ont accès à un partage d'audit en fonction de leur adresse IP. Accordez l'accès au partage d'audit à un nouveau client d'audit NFS en ajoutant son adresse IP au partage ou supprimez un client d'audit existant en supprimant son adresse IP.


