---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 'En tant qu"administrateur du grid, vous créez et gérez les comptes de locataire utilisés par les clients S3 et Swift pour stocker et récupérer des objets, surveiller l"utilisation du stockage et gérer les actions que les clients peuvent exécuter à l"aide de votre système StorageGRID.' 
---
= Gérer les locataires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En tant qu'administrateur du grid, vous créez et gérez les comptes de locataire utilisés par les clients S3 et Swift pour stocker et récupérer des objets, surveiller l'utilisation du stockage et gérer les actions que les clients peuvent exécuter à l'aide de votre système StorageGRID.



== Qu'est-ce qu'un compte de locataire ?

Les comptes de locataires permettent aux applications client qui utilisent l'API REST S3 (simple Storage Service) ou l'API REST Swift pour stocker et récupérer des objets dans StorageGRID.

Chaque compte de locataire prend en charge l'utilisation d'un protocole unique, que vous spécifiez lors de la création du compte. Pour stocker et récupérer des objets dans un système StorageGRID avec les deux protocoles, vous devez créer deux comptes de locataire : un pour les compartiments et objets S3, et un pour les conteneurs et objets Swift. Chaque compte de locataire possède son propre ID de compte, groupes et utilisateurs autorisés, compartiments ou conteneurs, et objets.

Vous pouvez également créer des comptes de tenant supplémentaires si vous souhaitez isoler les objets stockés sur votre système par des entités différentes. Par exemple, vous pouvez définir plusieurs comptes locataires dans l'un de ces cas d'utilisation :

* *Cas d'utilisation entreprise :* si vous gérez un système StorageGRID dans une application d'entreprise, vous pourriez vouloir isoler le stockage objet de la grille par les différents départements de votre organisation. Dans ce cas, vous pouvez créer des comptes de tenant pour le département Marketing, le service Customer support, le service des ressources humaines, etc.
+

NOTE: Si vous utilisez le protocole client S3, il vous suffit d'utiliser des compartiments S3 et des règles de compartiment pour isoler les objets entre les différents départements d'une entreprise. Vous n'avez pas besoin d'utiliser de comptes de tenant. Pour plus d'informations, consultez les instructions d'implémentation des applications client S3.

* *Cas d'utilisation de fournisseur de services :* si vous gérez un système StorageGRID en tant que fournisseur de services, vous pouvez isoler le stockage objet de la grille par les différentes entités qui loueront le stockage sur votre grille. Dans ce cas, vous créeriez des comptes de tenant pour la société A, la société B, la société C, etc.




== Créez et configurez les comptes de locataire

Lorsque vous créez un compte de locataire, vous spécifiez les informations suivantes :

* Afficher le nom du compte locataire.
* Quel protocole client sera utilisé par le compte de locataire (S3 ou Swift).
* Pour les comptes de locataire S3 : si le compte du locataire est autorisé à utiliser des services de plateforme avec des compartiments S3. Si vous autorisez les comptes locataires à utiliser des services de plateforme, vous devez vous assurer que la grille est configurée pour prendre en charge leur utilisation. Voir "Manage des services de plate-forme".
* Éventuellement, un quota de stockage pour le compte du locataire, soit le nombre maximal de gigaoctets, téraoctets ou pétaoctets disponibles pour les objets du locataire. Si le quota est dépassé, le locataire ne peut pas créer de nouveaux objets.
+

NOTE: Le quota de stockage d'un locataire représente une quantité logique (taille d'objet), et non une quantité physique (taille sur disque).

* Si la fédération des identités est activée pour le système StorageGRID, quel groupe fédéré a l'autorisation d'accès racine pour configurer le compte de tenant.
* Si l'authentification unique (SSO) n'est pas utilisée pour le système StorageGRID, que le compte de tenant utilise son propre référentiel d'identité ou partage le référentiel d'identité de la grille et le mot de passe initial de l'utilisateur racine local du locataire.


Une fois le compte de locataire créé, vous pouvez effectuer les tâches suivantes :

* *Gérer les services de plate-forme pour le grid* : si vous activez les services de plate-forme pour les comptes de tenant, assurez-vous de comprendre comment les messages de services de plate-forme sont fournis et les exigences de mise en réseau que l'utilisation des services de plate-forme place dans votre déploiement StorageGRID.
* *Surveiller l'utilisation du stockage d'un compte locataire* : lorsque les locataires commencent à utiliser leurs comptes, vous pouvez utiliser Grid Manager pour surveiller la quantité de stockage consommée par chaque locataire.
+

NOTE: Les valeurs d'utilisation du stockage d'un locataire peuvent devenir obsolètes si les nœuds sont isolés des autres nœuds de la grille. Les totaux seront mis à jour lorsque la connectivité réseau sera restaurée.

+
Si vous avez défini des quotas pour les locataires, vous pouvez activer l'alerte *usage du quota de locataires élevé* pour déterminer si les locataires consomment leurs quotas. Si elle est activée, cette alerte est déclenchée lorsqu'un locataire a utilisé 90 % de son quota. Pour plus d'informations, consultez la référence des alertes dans les instructions de surveillance et de dépannage de StorageGRID.

* *Configurer les opérations client* : vous pouvez configurer si certains types d'opérations client sont interdits.




== Configurez les locataires S3

Une fois le compte de locataire S3 créé, les utilisateurs peuvent accéder au Gestionnaire des locataires pour effectuer les tâches suivantes :

* Configuration de la fédération des identités (sauf si le référentiel d'identité est partagé avec la grille) et création de groupes et d'utilisateurs locaux
* Gestion des clés d'accès S3
* Création et gestion des compartiments S3
* Contrôle de l'utilisation du stockage
* Utilisation des services de plate-forme (si activé)



IMPORTANT: Les locataires S3 peuvent créer et gérer des compartiments et des clés d'accès S3 avec le gestionnaire des locataires. Cependant, ils doivent utiliser une application client S3 pour récupérer et gérer les objets.



== Configurez les locataires Swift

Une fois le compte de locataire Swift créé, l'utilisateur root du locataire peut accéder au Gestionnaire de locataires pour effectuer les tâches suivantes :

* Configuration de la fédération des identités (sauf si le référentiel d'identité est partagé avec la grille) et création de groupes et d'utilisateurs locaux
* Contrôle de l'utilisation du stockage



IMPORTANT: Les utilisateurs Swift doivent disposer de l'autorisation d'accès racine pour accéder au Gestionnaire de locataires. Toutefois, l'autorisation d'accès racine ne permet pas aux utilisateurs de s'authentifier auprès de l'API REST Swift pour créer des conteneurs et ingérer des objets. Les utilisateurs doivent disposer de l'autorisation Administrateur Swift pour s'authentifier dans l'API REST de Swift.

xref:../tenant/index.adoc[Utilisez un compte de locataire]
