---
permalink: admin/removing-user-or-group-from-cifs-audit-share.html 
sidebar: sidebar 
keywords: cifs audit client 
summary: 'Vous ne pouvez pas supprimer le dernier utilisateur ou groupe autorisé à accéder au partage d"audit.' 
---
= Supprimer un utilisateur ou un groupe d'un partage d'audit CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous ne pouvez pas supprimer le dernier utilisateur ou groupe autorisé à accéder au partage d'audit.

.Ce dont vous avez besoin, 8217;ll
* Vous avez le `Passwords.txt` Fichier avec les mots de passe du compte racine (disponible dans LEDIT package).
* Vous avez le `Configuration.txt` Fichier (disponible dans LEDIT paquet).


L'exportation d'audit via CIFS/Samba a été obsolète et sera supprimée dans une future version de StorageGRID.

.Étapes
. Connectez-vous au nœud d'administration principal :
+
.. Saisissez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Démarrez l'utilitaire de configuration CIFS : `config_cifs.rb`
+
[listing]
----

---------------------------------------------------------------------
| Shares                 | Authentication         | Config          |
---------------------------------------------------------------------
| add-audit-share        | set-authentication     | validate-config |
| enable-disable-share   | set-netbios-name       | help            |
| add-user-to-share      | join-domain            | exit            |
| remove-user-from-share | add-password-server    |                 |
| modify-group           | remove-password-server |                 |
|                        | add-wins-server        |                 |
|                        | remove-wins-server     |                 |
---------------------------------------------------------------------
----
. Commencez à supprimer un utilisateur ou un groupe : `remove-user-from-share`
+
Une liste numérotée des partages d'audit disponibles pour le nœud d'administration s'affiche. Le partage d'audit est étiqueté audit-export.

. Entrez le numéro du partage d'audit : `_audit_share_number_`
. Lorsque vous êtes invité à supprimer un utilisateur ou un groupe : `user` ou `group`
+
Une liste numérotée d'utilisateurs ou de groupes pour le partage d'audit s'affiche.

. Entrez le numéro correspondant à l'utilisateur ou au groupe que vous souhaitez supprimer : `_number_`
+
Le partage d'audit est mis à jour et l'utilisateur ou le groupe n'est plus autorisé à accéder au partage d'audit. Par exemple :

+
[listing]
----
Enabled shares
 1. audit-export
Select the share to change: 1
Remove user or group? [User/group]: User
Valid users for this share
1. audituser
2. newaudituser
Select the user to remove: 1

Removed user "audituser" from share "audit-export".

Press return to continue.
----
. Fermez l'utilitaire de configuration CIFS : `exit`
. Si le déploiement StorageGRID inclut des nœuds d'administration sur d'autres sites, désactivez le partage d'audit sur chaque site selon les besoins.
. Déconnectez-vous de chaque shell de commande une fois la configuration terminée : `exit`

