---
permalink: admin/scheduling-data-migration.html 
sidebar: sidebar 
keywords: data migration schedule, monitor data migration 
summary: La migration des données doit être planifiée et contrôlée si nécessaire pour assurer le placement des données conformément à la politique ILM dans les délais impartis. 
---
= Planifiez et surveillez la migration des données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La migration des données doit être planifiée et contrôlée si nécessaire pour assurer le placement des données conformément à la politique ILM dans les délais impartis.



== Planification de la migration des données

Évitez la migration des données pendant les heures de fonctionnement essentielles. Limitez la migration des données aux soirées, week-ends et autres fois que l'utilisation du système est faible.

Si possible, ne pas planifier de migration des données pendant les périodes d'activité élevée. Toutefois, s'il n'est pas pratique d'éviter complètement la période d'activité élevée, il est sûr de procéder aussi longtemps que vous surveillez attentivement les attributs pertinents et que vous prenez des mesures s'ils dépassent les valeurs acceptables.



== Surveiller la migration des données

Ce tableau répertorie les attributs que vous devez contrôler lors de la migration des données, ainsi que les problèmes qu'ils représentent.

Si vous utilisez des stratégies de classification du trafic avec des limites de taux pour accélérer l'entrée, vous pouvez surveiller le taux observé en conjonction avec les statistiques décrites dans le tableau suivant et réduire les limites si nécessaire.

[cols="1a,2a"]
|===
| Superviser | Description 


 a| 
Nombre d'objets en attente de l'évaluation ILM
 a| 
. Sélectionnez *SUPPORT* > *Outils* > *topologie de grille*.
. Sélectionnez *_déploiement_* *Présentation* *main*.
. Dans la section ILM Activity, surveillez le nombre d'objets affichés pour les attributs suivants :
+
** *Attente - tous (XQUZ)*: Le nombre total d'objets en attente d'évaluation ILM.
** *Attente - client (XCQZ)* : nombre total d'objets en attente d'évaluation ILM des opérations client (par exemple, transfert).


. Si le nombre d'objets affichés pour l'un de ces attributs dépasse 100,000, réduisez la vitesse d'entrée des objets afin de réduire la charge sur le système StorageGRID.




 a| 
Capacité de stockage des systèmes d'archivage ciblés
 a| 
Si la règle ILM enregistre une copie des données migrées vers un système de stockage d'archives ciblé (bande ou cloud), surveillez la capacité du système de stockage d'archivage ciblé pour s'assurer que la capacité disponible est suffisante.



 a| 
*Archive Node* *ARC* *Store*
 a| 
Si une alarme pour l'attribut *Store Failures (ARVF)* est déclenchée, le système de stockage d'archives ciblé a peut-être atteint sa capacité. Vérifiez le système de stockage d'archives ciblé et résolvez tout problème ayant déclenché une alarme.

|===