---
permalink: admin/supported-ciphers-for-outgoing-tls-connections.html 
sidebar: sidebar 
keywords: tls cipher suites, transport layer security connections 
summary: 'Le système StorageGRID prend en charge un ensemble limité de suites de chiffrement pour les connexions \(TLS\) de la couche de transport aux systèmes externes utilisés pour la fédération des identités et les pools de stockage cloud.' 
---
= Chiffrement pris en charge pour les connexions TLS sortantes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système StorageGRID prend en charge un ensemble limité de suites de chiffrement pour les connexions TLS (transport Layer Security) avec les systèmes externes utilisés pour la fédération des identités et les pools de stockage cloud.



== Versions supportées de TLS

StorageGRID prend en charge TLS 1.2 et TLS 1.3 pour les connexions aux systèmes externes utilisés pour la fédération des identités et les pools de stockage cloud.

Les chiffrements TLS qui sont pris en charge pour une utilisation avec des systèmes externes ont été sélectionnés pour assurer la compatibilité avec une gamme de systèmes externes. La liste est plus grande que la liste des chiffrements pris en charge pour une utilisation avec les applications client S3 ou Swift.


NOTE: Les options de configuration TLS telles que les versions de protocole, les chiffrements, les algorithmes d'échange de clés et les algorithmes MAC ne sont pas configurables en StorageGRID. Contactez votre ingénieur commercial NetApp pour toute demande spécifique concernant ces paramètres.



== Suites de chiffrement TLS 1.2 prises en charge

Les suites de chiffrement TLS 1.2 suivantes sont prises en charge :

* TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
* TLS_ECDHE_RSA_WITH_CHA20_POLY1305
* TLS_ECDHE_ECDSA_WITH_CHA20_POLY1305
* TLS_RSA_WAS_AES_128_GCM_SHA256
* TLS_RSA_WITH_AES_256_GCM_SHA384




== Suites de chiffrement TLS 1.3 prises en charge

Les suites de chiffrement TLS 1.3 suivantes sont prises en charge :

* TLS_AES_256_GCM_SHA384
* TLS_CHA20_POLY1305_SHA256
* TLS_AES_128_GCM_SHA256

