---
permalink: s3/recommendations-for-implementing-s3-rest-api.html 
sidebar: sidebar 
keywords: implement s3 rest api 
summary: 'Suivez ces recommandations lors de l"implémentation de l"API REST S3 pour une utilisation avec StorageGRID.' 
---
= Recommandations pour l'implémentation de l'API REST S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces recommandations lors de l'implémentation de l'API REST S3 pour une utilisation avec StorageGRID.



== Recommandations pour les têtes à des objets inexistants

Si votre application vérifie régulièrement si un objet existe sur un chemin où vous ne vous attendez pas à ce que l'objet existe réellement, vous devez utiliser le contrôle de cohérence « disponible ». Par exemple, vous devez utiliser le contrôle de cohérence « disponible » si votre application dirige un emplacement avant DE LE PLACER.

Sinon, si l'opération HEAD ne trouve pas l'objet, vous pouvez recevoir un nombre élevé de 500 erreurs de serveur interne si un ou plusieurs nœuds de stockage ne sont pas disponibles.

Vous pouvez définir le contrôle de cohérence « disponible » pour chaque compartiment à l'aide de la demande DE cohérence PUT bucket, ou spécifier le contrôle de cohérence dans l'en-tête de demande pour une opération API individuelle.



== Recommandations pour les clés d'objet

Pour les compartiments créés dans StorageGRID 11.4 ou version ultérieure, il n'est plus nécessaire de limiter les noms de clés d'objet afin de respecter les meilleures pratiques en matière de performances. Par exemple, vous pouvez maintenant utiliser des valeurs aléatoires pour les quatre premiers caractères des noms de clés d'objet.

Pour les compartiments créés dans les versions antérieures à StorageGRID 11.4, suivez les recommandations suivantes pour les noms de clés d'objet :

* Vous ne devez pas utiliser de valeurs aléatoires comme les quatre premiers caractères des clés d'objet. Cela contraste avec l'ancienne recommandation AWS pour les préfixes de clés. Au lieu de cela, vous devez utiliser des préfixes non aléatoires et non uniques, tels que `image`.
* Si vous suivez l'ancienne recommandation AWS pour utiliser des caractères aléatoires et uniques dans les préfixes de clés, vous devez préfixer les clés d'objet avec un nom de répertoire. C'est-à-dire, utilisez le format suivant :
+
[listing]
----
mybucket/mydir/f8e3-image3132.jpg
----
+
Au lieu de ce format :

+
[listing]
----
mybucket/f8e3-image3132.jpg
----




== Recommandations pour les « lectures de plage »

Si l'option *Compress Stored Objects* est sélectionnée (*CONFIGURATION* *système* *Grid options*), les applications client S3 doivent éviter d'effectuer des opérations GET Object qui indiquent une plage d'octets. Ces opérations de « lecture à plage » sont inefficaces, car StorageGRID doit décompresser efficacement les objets pour accéder aux octets demandés. LES opérations GET Object qui demandent une petite plage d'octets provenant d'un objet très volumineux sont particulièrement inefficaces. Par exemple, il est très inefficace de lire une plage de 10 Mo à partir d'un objet compressé de 50 Go.

Si les plages sont lues à partir d'objets compressés, les demandes client peuvent être en attente.


NOTE: Si vous devez compresser des objets et que votre application client doit utiliser des lectures de plage, augmentez le délai de lecture de l'application.

.Informations associées
* xref:consistency-controls.adoc[Contrôles de cohérence]
* xref:put-bucket-consistency-request.adoc[PUT Bucket Consistency demandée]
* xref:../admin/index.adoc[Administrer StorageGRID]

