---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 'Si vous souhaitez surveiller StorageGRID à l"aide du protocole simple de gestion de réseau \(SNMP\), vous devez configurer l"agent SNMP inclus avec StorageGRID.' 
---
= Utiliser la surveillance SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez surveiller StorageGRID à l'aide du protocole SNMP (simple Network Management Protocol), vous devez configurer l'agent SNMP inclus avec StorageGRID.

* xref:configuring-snmp-agent.adoc[Configurez l'agent SNMP]
* xref:updating-snmp-agent.adoc[Mettez à jour l'agent SNMP]




== Capacités

Chaque nœud StorageGRID exécute un agent SNMP, ou un démon, qui fournit une base d'informations de gestion (MIB). La MIB StorageGRID contient des définitions de tableau et de notification pour les alertes et les alarmes. La base MIB contient également des informations de description du système, telles que la plateforme et le numéro de modèle pour chaque nœud. Chaque nœud StorageGRID supporte également un sous-ensemble d'objets MIB-II.

Au départ, le protocole SNMP est désactivé sur tous les nœuds. Lorsque vous configurez l'agent SNMP, tous les nœuds StorageGRID reçoivent la même configuration.

L'agent SNMP StorageGRID prend en charge les trois versions du protocole SNMP. Il fournit un accès MIB en lecture seule pour les requêtes et il peut envoyer deux types de notifications événementielle à un système de gestion :

* *Les traps* sont des notifications envoyées par l'agent SNMP qui ne nécessitent pas d'accusé de réception par le système de gestion. Les interruptions servent à signaler au système de gestion qu'une alerte s'est produite au sein de StorageGRID, par exemple.
+
Les traps sont pris en charge dans les trois versions de SNMP.

* *Inform* sont similaires aux pièges, mais ils exigent une reconnaissance du système de gestion. Si l'agent SNMP ne reçoit pas d'accusé de réception dans un certain temps, il renvoie l'information jusqu'à ce qu'un accusé de réception soit reçu ou que la valeur de nouvelle tentative maximale ait été atteinte.
+
Les informations sont prises en charge dans SNMPv2c et SNMPv3.



Les notifications d'interruption et d'information sont envoyées dans les cas suivants :

* Une alerte par défaut ou personnalisée est déclenchée à tout niveau de gravité. Pour supprimer les notifications SNMP pour une alerte, vous devez configurer un silence pour l'alerte. Les notifications d'alerte sont envoyées par n'importe quel nœud d'administration configuré pour être l'expéditeur préféré.
+
Chaque alerte est associée à l'un des trois types de déroutement en fonction du niveau de gravité de l'alerte : activeMinorAlert, activeMajorAlert et activeCriticalAlert. Pour obtenir des descriptions des alertes qui peuvent déclencher ces interruptions, reportez-vous au xref:alerts-reference.adoc[Référence des alertes].

* Certaines alarmes (système hérité) sont déclenchées à des niveaux de gravité spécifiés ou plus.
+

NOTE: Les notifications SNMP ne sont pas envoyées pour chaque alarme ou chaque gravité d'alarme.





== Prise en charge de la version SNMP

Le tableau fournit un résumé détaillé des éléments pris en charge pour chaque version de SNMP.

|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
Requêtes
 a| 
Requêtes MIB en lecture seule
 a| 
Requêtes MIB en lecture seule
 a| 
Requêtes MIB en lecture seule



 a| 
Authentification par requête
 a| 
Chaîne de communauté
 a| 
Chaîne de communauté
 a| 
Utilisateur USM (User Security Model)



 a| 
Notifications
 a| 
Traps uniquement
 a| 
Pièges et information
 a| 
Pièges et information



 a| 
Authentification des notifications
 a| 
Communauté d'interruptions par défaut ou chaîne de communauté personnalisée pour chaque destination d'interruption
 a| 
Communauté d'interruptions par défaut ou chaîne de communauté personnalisée pour chaque destination d'interruption
 a| 
Utilisateur USM pour chaque destination d'interruption

|===


== Limites

* StorageGRID supporte l'accès MIB en lecture seule. L'accès en lecture/écriture n'est pas pris en charge.
* Tous les nœuds de la grille reçoivent la même configuration.
* SNMPv3 : StorageGRID ne prend pas en charge le mode support transport (TSM).
* SNMPv3 : le seul protocole d'authentification pris en charge est SHA (HMAC-SHA-96).
* SNMPv3 : le seul protocole de confidentialité pris en charge est AES.




== Accéder à la MIB

Vous pouvez accéder au fichier de définition MIB à l'emplacement suivant sur n'importe quel nœud StorageGRID :

`/usr/share/snmp/mibs/NETAPP-STORAGEGRID-MIB.txt`

.Informations associées
* xref:alerts-reference.adoc[Référence des alertes]
* xref:alarms-reference.adoc[Référence des alarmes (système hérité)]
* xref:alarms-that-generate-snmp-notifications.adoc[Alarmes générant des notifications SNMP (système hérité)]
* xref:silencing-alert-notifications.adoc[Notifications d'alerte de silence]

