---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: 'Vous pouvez ajouter, mettre à jour ou supprimer des serveurs NTP (Network Time Protocol) afin de vous assurer que les données sont synchronisées précisément entre les nœuds de la grille de votre système StorageGRID.' 
---
= Configurer des serveurs NTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter, mettre à jour ou supprimer des serveurs NTP (Network Time Protocol) afin de vous assurer que les données sont synchronisées précisément entre les nœuds grid de votre système StorageGRID.

.Ce dont vous avez besoin
* Vous devez être connecté au Grid Manager à l'aide d'un xref:../admin/web-browser-requirements.adoc[navigateur web pris en charge].
* Vous devez disposer de l'autorisation Maintenance ou accès racine.
* Vous devez disposer de la phrase secrète pour le provisionnement.
* Les adresses IPv4 des serveurs NTP à configurer doivent être définies.


.Description de la tâche
Le système StorageGRID utilise le protocole NTP (Network Time Protocol) pour synchroniser l'heure entre tous les nœuds de la grille.

Le rôle NTP principal est attribué à chaque site au moins deux nœuds du système StorageGRID. Ils se synchronisent avec un minimum suggéré de quatre et un maximum de six sources de temps externes et entre elles. Chaque nœud du système StorageGRID qui n'est pas un nœud NTP principal agit comme un client NTP et se synchronise avec ces nœuds NTP primaires.

Les serveurs NTP externes se connectent aux nœuds auxquels vous avez précédemment attribué des rôles NTP primaires. Pour cette raison, il est recommandé de spécifier au moins deux nœuds avec les rôles NTP principaux.


IMPORTANT: Assurez-vous qu'au moins deux nœuds de chaque site peuvent accéder à au moins quatre sources NTP externes. Si un seul nœud d'un site peut atteindre les sources NTP, des problèmes de synchronisation surviennent en cas de panne de ce nœud. En outre, la désignation de deux nœuds par site en tant que sources NTP principales assure une synchronisation précise si un site est isolé du reste de la grille.

Les serveurs NTP externes spécifiés doivent utiliser le protocole NTP. Vous devez spécifier les références de serveur NTP de Stratum 3 ou mieux pour éviter les problèmes de dérive du temps.


NOTE: Lorsque vous spécifiez la source NTP externe pour une installation StorageGRID au niveau de la production, n'utilisez pas le service Windows Time (W32Time) sur une version de Windows antérieure à Windows Server 2016. Le service de temps des versions antérieures de Windows n'est pas suffisamment précis et n'est pas pris en charge par Microsoft pour une utilisation dans des environnements à haute précision, tels que StorageGRID.

https://["Limite de prise en charge pour configurer le service de temps Windows pour des environnements de haute précision"^]

Si vous rencontrez des problèmes de stabilité ou de disponibilité des serveurs NTP initialement spécifiés lors de l'installation, vous pouvez mettre à jour la liste des sources NTP externes que le système StorageGRID utilise en ajoutant des serveurs supplémentaires ou en mettant à jour ou en supprimant des serveurs existants.

.Étapes
. Sélectionnez *MAINTENANCE* *réseau* *serveurs NTP*.
. Dans la section serveurs, ajoutez des mises à jour ou supprimez des entrées de serveur NTP, si nécessaire.
+
Vous devez inclure au moins 4 serveurs NTP, et vous pouvez spécifier jusqu'à 6 serveurs.

. Dans la zone de texte *Provisioning Passphrase* (phrase de passe de provisionnement), saisissez le mot de passe de provisionnement de votre système StorageGRID et cliquez sur *Save* (Enregistrer).
+
L'état de la procédure s'affiche en haut de la page. La page est désactivée jusqu'à ce que les mises à jour de la configuration soient terminées.

+

IMPORTANT: Si tous vos serveurs NTP échouent au test de connexion après avoir enregistré les nouveaux serveurs NTP, ne continuez pas. Contactez l'assistance technique.


