---
permalink: maintain/deploying-new-linux-hosts.html 
sidebar: sidebar 
keywords: storagegrid, deploy linux host, new host, new linux host 
summary: 'À quelques exceptions près, vous préparez les nouveaux hôtes comme vous l"avez fait lors du processus d"installation initiale.' 
---
= Déploiement de nouveaux hôtes Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À quelques exceptions près, vous préparez les nouveaux hôtes comme vous l'avez fait lors du processus d'installation initiale.

Pour déployer de nouveaux hôtes physiques ou virtuels Linux, suivez la procédure de préparation des hôtes dans les instructions d'installation de StorageGRID pour votre système d'exploitation Linux.

Cette procédure comprend les étapes permettant d'effectuer les tâches suivantes :

. Installez Linux.
. Configurez le réseau hôte.
. Configurer le stockage de l'hôte
. Installer le moteur de mise en conteneurs.
. Installez le service hôte StorageGRID.
+

IMPORTANT: Arrêtez-vous après avoir terminé la tâche « installer le service hôte StorageGRID » dans les instructions d'installation. Ne démarrez pas la tâche "noeuds de grille de distribution".



À mesure que vous effectuez ces étapes, prenez note des consignes importantes suivantes :

* Veillez à utiliser les mêmes noms d'interface hôte que ceux utilisés sur l'hôte d'origine.
* Si vous utilisez le stockage partagé pour prendre en charge vos nœuds StorageGRID, ou si vous avez déplacé certains ou l'ensemble des disques ou disques SSD de vers les nœuds de remplacement, vous devez rétablir les mappages de stockage présents sur l'hôte d'origine. Par exemple, si vous avez utilisé des WWID et des alias dans `/etc/multipath.conf` Comme recommandé dans les instructions d'installation, veillez à utiliser les mêmes paires alias/WWID dans `/etc/multipath.conf` sur l'hôte de remplacement.
* Si le nœud StorageGRID utilise le stockage affecté à un système NetApp ONTAP, vérifiez que cette FabricPool règle n'est pas activée pour le volume. La désactivation du Tiering FabricPool pour les volumes utilisés avec des nœuds StorageGRID simplifie la résolution des problèmes et les opérations de stockage.
+

IMPORTANT: N'utilisez jamais FabricPool pour transférer automatiquement toutes les données liées à StorageGRID vers StorageGRID. Le Tiering des données StorageGRID vers StorageGRID augmente la complexité opérationnelle et la résolution des problèmes.



.Informations associées
xref:../rhel/index.adoc[Installez Red Hat Enterprise Linux ou CentOS]

xref:../ubuntu/index.adoc[Installez Ubuntu ou Debian]
