---
permalink: maintain/installing-services-appliance-platform-change-only.html 
sidebar: sidebar 
keywords: storagegrid, recover services appliance, recover appliance, recovering appliance, recovering services appliance, install services appliance, installing services appliance, services appliance 
summary: 'Lorsque vous récupérez un nœud de grille défaillant hébergé sur un hôte VMware ou Linux et que vous utilisez une appliance de services SG100 ou SG1000 pour le nœud de remplacement, vous devez d"abord installer le nouveau matériel d"appliance en utilisant le même nom de nœud que le nœud défaillant.' 
---
= Installer l'appliance de services (changement de plateforme uniquement)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous récupérez un nœud de grille défaillant hébergé sur un hôte VMware ou Linux et que vous utilisez une appliance de services SG100 ou SG1000 pour le nœud de remplacement, vous devez d'abord installer le nouveau matériel d'appliance en utilisant le même nom de nœud que le nœud défaillant.

Vous devez disposer des informations suivantes concernant le nœud défaillant :

* *Nom du noeud* : vous devez installer l'appliance de services en utilisant le même nom de noeud que le noeud défaillant.
* *Adresses IP* : vous pouvez attribuer à l'appliance de services les mêmes adresses IP que le nœud défaillant, qui est l'option préférée, ou sélectionner une nouvelle adresse IP inutilisée sur chaque réseau.


Effectuez cette procédure uniquement si vous récupérez un noeud défaillant hébergé sur VMware ou Linux et que vous le remplacez par un noeud hébergé sur une appliance de services.

. Suivez les instructions d'installation d'un nouvel appareil de services SG100 ou SG1000.
. Lorsqu'un nom de nœud est demandé, utilisez le nom du nœud correspondant à l'échec.


.Informations associées
xref:../sg100-1000/index.adoc[Appareils de services SG100 et SG1000]
