---
permalink: maintain/rebooting-grid-node.html 
sidebar: sidebar 
keywords: reboot grid node 
summary: Vous pouvez redémarrer un nœud de grille à partir de Grid Manager ou depuis le shell de commande du nœud. 
---
= Redémarrez le nœud de la grille
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez redémarrer un nœud grid à partir de Grid Manager ou depuis le shell de commande du nœud.

.Description de la tâche
Lorsque vous redémarrez un nœud de la grille, celui-ci s'arrête et redémarre. Tous les services sont redémarrés automatiquement.

Si vous prévoyez de redémarrer les nœuds de stockage, notez les éléments suivants :

* Si une règle ILM spécifie un comportement d'entrée de la double allocation ou si la règle indique un équilibrage et qu'il n'est pas possible de créer immédiatement toutes les copies nécessaires, StorageGRID valide immédiatement les objets récemment ingérées sur deux nœuds de stockage du même site, et évalue la ILM plus tard. Si vous souhaitez redémarrer deux ou plusieurs nœuds de stockage sur un site donné, il se peut que vous ne puissiez pas accéder à ces objets pendant la durée du redémarrage.
* Pour vous assurer que vous pouvez accéder à tous les objets lors du redémarrage d'un nœud de stockage, arrêtez de les ingérer sur un site pendant environ une heure avant de redémarrer le nœud.


.Informations associées
xref:../admin/index.adoc[Administrer StorageGRID]
