---
permalink: maintain/removing-donotstart-file-for-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, donotstart file, do not start file, remove donotstart, removing donotstart, remove do not start, removing do not start 
summary: 'Lorsque vous supprimez un fichier DoNotStart qui empêche le démarrage d"un service, vous devez démarrer ce service.' 
---
= Supprimez le fichier DoNotStart pour le service
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous supprimez un fichier DoNotStart qui empêche le démarrage d'un service, vous devez démarrer ce service.

.Ce dont vous avez besoin
Vous devez avoir le `Passwords.txt` fichier.

.Étapes
. Connectez-vous au nœud grid :
+
.. Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.

. Supprimez le fichier DoNotStart du répertoire de services : `rm /etc/sv/_service_/DoNotStart`
+
où `service` est le nom du service. Par exemple :

+
[listing]
----
rm /etc/sv/ldr/DoNotStart
----
. Démarrer le service : `service _servicename_ start`
. Déconnectez-vous du shell de commande : `exit`

