---
permalink: maintain/replacing-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace storage node, replacing storage node 
summary: 'Si le lecteur du système est défectueux, vous devez d"abord remplacer le nœud de stockage.' 
---
= Remplacez le nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le lecteur du système est défectueux, vous devez d'abord remplacer le nœud de stockage.

Vous devez sélectionner la procédure de remplacement de nœuds pour votre plate-forme. Les étapes à suivre pour remplacer un nœud sont les mêmes pour tous les types de nœuds de la grille.


NOTE: Cette procédure s'applique uniquement aux nœuds de stockage basés sur logiciel. Vous devez suivre une procédure différente pour restaurer un nœud de stockage d'appliance.

xref:recovering-storagegrid-appliance-storage-node.adoc[Restaurez le nœud de stockage de l'appliance]

*Linux:* si vous n'êtes pas sûr que votre lecteur système a échoué, suivez les instructions pour remplacer le nœud afin de déterminer quelles étapes de restauration sont nécessaires.

[cols="1a,2a"]
|===
| Plateforme | Procédure 


 a| 
VMware
 a| 
xref:all-node-types-replacing-vmware-node.adoc[Remplacement d'un noeud VMware]



 a| 
Linux
 a| 
xref:all-node-types-replacing-linux-node.adoc[Remplacer un noeud Linux]



 a| 
OpenStack
 a| 
Les fichiers et scripts de disques de machine virtuelle fournis par NetApp pour OpenStack ne sont plus pris en charge pour les opérations de restauration. Si vous devez restaurer un nœud exécuté dans un déploiement OpenStack, téléchargez les fichiers du système d'exploitation Linux. Suivez ensuite la procédure de remplacement d'un noeud Linux.

|===