---
permalink: maintain/replacing-failed-node-with-services-appliance.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace failed node, services appliance 
summary: 'Vous pouvez utiliser une appliance de services SG100 ou SG1000 pour récupérer un nœud de passerelle défaillant, un nœud d"administration non primaire défaillant ou un nœud d"administration principal défaillant hébergé sur VMware, un hôte Linux ou une appliance de services. Cette procédure constitue une étape de la procédure de restauration des nœuds de la grille.' 
---
= Remplacez le nœud défectueux par l'appliance de services
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser une appliance de services SG100 ou SG1000 pour récupérer un nœud de passerelle défaillant, un nœud d'administration non primaire défaillant ou un nœud d'administration principal défaillant hébergé sur VMware, un hôte Linux ou une appliance de services. Cette procédure constitue une étape de la procédure de restauration des nœuds de la grille.

.Ce dont vous avez besoin, 8217;ll
* Vous devez avoir déterminé que l'une des situations suivantes est vraie :
+
** Impossible de restaurer la machine virtuelle hébergeant le nœud.
** L'hôte Linux physique ou virtuel du nœud grid a échoué et doit être remplacé.
** L'appliance de services qui héberge le nœud de grid doit être remplacée.


* Assurez-vous que la version du programme d'installation de l'appliance StorageGRID installée sur l'appliance de services correspond à la version logicielle de votre système StorageGRID, comme décrit dans installation et maintenance du matériel pour vérifier et mettre à niveau la version du programme d'installation de l'appliance StorageGRID.
+
xref:../sg100-1000/index.adoc[Appareils de services SG100 et SG1000]




IMPORTANT: Ne déployez pas un appareil SG100 et un appareil SG1000 sur le même site. Cela peut entraîner des performances imprévisibles.

Vous pouvez utiliser une appliance de services SG100 ou SG1000 pour restaurer un nœud de grille défaillant dans les cas suivants :

* Le nœud en panne était hébergé sur VMware ou Linux (changement de plateforme)
* Le nœud en panne était hébergé sur une appliance de services (remplacement de plateforme)

