---
permalink: maintain/restoring-and-validating-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore grid node, restore node, validate grid node, validate node 
summary: Vous devez restaurer les fichiers de configuration de la grille de tout nœud de grille ayant échoué, puis valider les fichiers de configuration de la grille et résoudre les erreurs éventuelles. 
---
= Restaurez et validez les nœuds de la grille
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez restaurer les fichiers de configuration de la grille de tout nœud de grille ayant échoué, puis valider les fichiers de configuration de la grille et résoudre les erreurs éventuelles.

.Description de la tâche
Vous pouvez importer tout nœud de grille qui doit être présent sur l'hôte, tant que son `/var/local` le volume n'a pas été perdu suite à la défaillance de l'hôte précédent. Par exemple, le `/var/local` Il se peut que le volume existe toujours si vous utilisez le stockage partagé pour les volumes de données du système StorageGRID, comme décrit dans les instructions d'installation de StorageGRID pour votre système d'exploitation Linux. L'importation du nœud restaure son fichier de configuration de nœud vers l'hôte.

S'il n'est pas possible d'importer des nœuds manquants, vous devez recréer leurs fichiers de configuration de grille.

Vous devez ensuite valider le fichier de configuration de la grille et résoudre tous les problèmes de réseau ou de stockage qui pourraient se produire avant de redémarrer StorageGRID. Lorsque vous recréez le fichier de configuration d'un nœud, vous devez utiliser le même nom pour le nœud de remplacement utilisé pour le nœud en cours de restauration.

Reportez-vous aux instructions d'installation pour plus d'informations sur l'emplacement du `/var/local` volume pour un nœud.

.Étapes
. Sur la ligne de commande de l'hôte restauré, répertoriez tous les nœuds grid StorageGRID actuellement configurés :``sudo storagegrid node list``
+
Si aucun nœud de grille n'est configuré, il n'y aura pas de sortie. Si certains nœuds de grid sont configurés, la sortie doit être au format suivant :

+
[listing]
----
Name               Metadata-Volume
================================================================
dc1-adm1           /dev/mapper/sgws-adm1-var-local
dc1-gw1            /dev/mapper/sgws-gw1-var-local
dc1-sn1            /dev/mapper/sgws-sn1-var-local
dc1-arc1           /dev/mapper/sgws-arc1-var-local
----
+
Si certains ou la totalité des nœuds de la grille qui doivent être configurés sur l'hôte ne sont pas répertoriés, vous devez restaurer les nœuds de la grille manquants.

. Pour importer des nœuds de grille dotés d'un `/var/local` volume :
+
.. Exécutez la commande suivante pour chaque nœud à importer :``sudo storagegrid node import node-var-local-volume-path``
+
Le `storagegrid node import` la commande ne réussit que si le nœud cible a été arrêté correctement sur l'hôte sur lequel il a été exécuté pour la dernière fois. Si ce n'est pas le cas, vous observez une erreur semblable à ce qui suit :

+
`This node (_node-name_) appears to be owned by another host (UUID host-uuid).`

+
`Use the --force flag if you are sure import is safe.`

.. Si vous voyez l'erreur relative au nœud qui appartient à un autre hôte, exécutez de nouveau la commande avec le `--force` indicateur pour terminer l'importation :``sudo storagegrid --force node import node-var-local-volume-path``
+

NOTE: Tous les nœuds importés avec le `--force` flag nécessitera des étapes de récupération supplémentaires avant qu'elles ne puissent rejoindre la grille, comme décrit dans xref:whats-next-performing-additional-recovery-steps-if-required.adoc[Qu'est-ce qui suit : effectuez d'autres étapes de restauration, le cas échéant].



. Pour les nœuds grid qui n'ont pas de `/var/local` volume, recréez le fichier de configuration du nœud pour le restaurer sur l'hôte.
+
Suivez les instructions de la section « Créer des fichiers de configuration de nœud » dans les instructions d'installation.

+

IMPORTANT: Lorsque vous recréez le fichier de configuration d'un nœud, vous devez utiliser le même nom pour le nœud de remplacement utilisé pour le nœud en cours de restauration. Pour les déploiements Linux, assurez-vous que le nom du fichier de configuration contient le nom du nœud. Lorsque cela est possible, vous devez utiliser les mêmes interfaces réseau, les mêmes mappages de périphériques de bloc et les mêmes adresses IP. Cette pratique réduit la quantité de données à copier sur le nœud lors de la restauration, ce qui peut accélérer la restauration (dans certains cas, quelques minutes au lieu de plusieurs semaines).

+

IMPORTANT: Si vous utilisez de nouveaux périphériques de bloc (périphériques que le nœud StorageGRID n'utilisait pas auparavant) comme valeurs pour l'une des variables de configuration commençant par `BLOCK_DEVICE_` lorsque vous recréez le fichier de configuration d'un nœud, veillez à suivre toutes les instructions de la section xref:fixing-missing-block-device-errors.adoc[Corrigez les erreurs de périphérique de bloc manquantes].

. Exécutez la commande suivante sur l'hôte restauré pour lister tous les nœuds StorageGRID.
+
`sudo storagegrid node list`

. Valider le fichier de configuration de nœud pour chaque nœud de la grille dont le nom s'affiche dans la sortie de la liste des nœuds StorageGRID :
+
`sudo storagegrid node validate _node-name_`

+
Vous devez corriger toute erreur ou avertissement avant de démarrer le service hôte StorageGRID. Les sections suivantes donnent plus de détails sur les erreurs susceptibles d'avoir une importance particulière pendant la récupération.



.Informations associées
xref:../rhel/index.adoc[Installez Red Hat Enterprise Linux ou CentOS]

xref:../ubuntu/index.adoc[Installez Ubuntu ou Debian]

xref:fixing-mssing-network-interface-errors.adoc[Corrigez les erreurs d'interface réseau manquantes]
