---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: 'Avant de restaurer un lecteur système défectueux d"un nœud de stockage, vous devez vérifier les avertissements suivants.' 
---
= Consultez les avertissements relatifs à la restauration du lecteur système du nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de restaurer un lecteur système défectueux d'un nœud de stockage, vous devez vérifier les avertissements suivants.

Les nœuds de stockage disposent d'une base de données Cassandra qui inclut les métadonnées d'objet. La base de données Cassandra peut être reconstruite dans les cas suivants :

* Un nœud de stockage est remis en ligne après avoir été hors ligne pendant plus de 15 jours.
* Un volume de stockage a échoué et a été récupéré.
* Le lecteur système et un ou plusieurs volumes de stockage sont défectueux et restaurés.


Lorsque Cassandra est reconstruite, le système utilise les informations d'autres nœuds de stockage. Si trop de nœuds de stockage sont hors ligne, il se peut que certaines données Cassandra ne soient pas disponibles. Si Cassandra a été récemment reconstruite, les données Cassandra ne peuvent pas encore être cohérentes sur l'ensemble de la grille. Cette perte peut se produire si Cassandra est reconstruite lorsque trop de nœuds de stockage sont hors ligne ou si deux nœuds de stockage ou plus sont reconstruites dans les 15 jours restants.


CAUTION: Si plusieurs nœuds de stockage ont échoué (ou sont hors ligne), contactez le support technique. Ne pas effectuer la procédure de récupération suivante. Des données peuvent être perdues.


CAUTION: S'il s'agit de la défaillance du deuxième nœud de stockage dans les 15 jours qui suivent la défaillance ou la restauration d'un nœud de stockage, contactez le support technique. Reconstruire Cassandra sur deux nœuds de stockage ou plus en un délai de 15 jours peut entraîner une perte de données.


NOTE: Si plusieurs nœuds de stockage d'un site ont échoué, une procédure de restauration de site peut être nécessaire. Contactez l'assistance technique.

xref:how-site-recovery-is-performed-by-technical-support.adoc[Comment la reprise sur site est effectuée par le support technique]


CAUTION: Si ce nœud de stockage est en mode de maintenance en lecture seule pour permettre la récupération d'objets par un autre nœud de stockage avec des volumes de stockage défaillants, récupérez les volumes du nœud de stockage avec des volumes de stockage défaillants avant de récupérer ce noeud de stockage défaillant. Reportez-vous aux instructions de restauration en cas de perte de volumes de stockage sur lesquels le lecteur système est intact.


IMPORTANT: Si les règles ILM sont configurées pour ne stocker qu'une seule copie répliquée, et si cette copie existe sur un volume de stockage défaillant, vous ne pourrez pas restaurer l'objet.


NOTE: Si vous rencontrez une alarme Services : Etat - Cassandra (SVST) pendant la récupération, reportez-vous aux instructions de surveillance et de dépannage pour récupérer de l'alarme en reconstruisant Cassandra. Après la reconstruction de Cassandra, les alarmes doivent être désactivées. Si les alarmes ne sont pas claires, contactez le support technique.

.Informations associées
xref:../monitor/index.adoc[Surveiller et résoudre les problèmes]

xref:warnings-and-considerations-for-grid-node-recovery.adoc[Avertissements et considérations relatives à la restauration des nœuds de la grille]

xref:recovering-from-storage-volume-failure-where-system-drive-is-intact.adoc[Restaurez le disque d'après la panne du volume de stockage là où le disque du système est intact]
