---
permalink: sg5700/hardware-setup-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: 'Il est possible que le programme d"installation de l"appliance StorageGRID ne soit pas disponible si des défaillances matérielles ou des erreurs de câblage empêchent le contrôleur E5700SG de terminer son processus de démarrage.' 
---
= La configuration du matériel semble être suspendue (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il est possible que le programme d'installation de l'appliance StorageGRID ne soit pas disponible si des défaillances matérielles ou des erreurs de câblage empêchent le contrôleur E5700SG de terminer son processus de démarrage.

.Étapes
. Observez les codes sur les affichages à sept segments.
+
Pendant l'initialisation du matériel pendant la mise sous tension, les deux affichages à sept segments affichent une séquence de codes. Lorsque le matériel démarre correctement, les sept segments affichent des codes différents pour chaque contrôleur.

. Examiner les codes sur l'affichage à sept segments du contrôleur E5700SG.
+

NOTE: L'installation et le provisionnement prennent du temps. Certaines phases d'installation ne signalent pas les mises à jour du programme d'installation de l'appliance StorageGRID pendant plusieurs minutes.

+
En cas d'erreur, l'affichage à sept segments clignote une séquence, telle QU'IL.

. Pour comprendre la signification de ces codes, consultez les ressources suivantes :
+
|===
| Contrôleur | Référence 


 a| 
Contrôleur E5700SG
 a| 
** "Indicateurs d'état sur le contrôleur E5700SG"
** « Erreur : erreur lors de la synchronisation avec le logiciel SANtricity OS »




 a| 
Contrôleur E2800
 a| 
_E5700 et E2800 System Monitoring Guide_

*Remarque :* les codes décrits pour le contrôleur E5700 E-Series ne s'appliquent pas au contrôleur E5700SG de l'appareil.

|===
. Si ce n'est pas le cas, contactez le support technique.


.Informations associées
xref:status-indicators-on-e5700sg-controller.adoc[Voyants d'état sur le contrôleur E5700SG]

xref:he-error-error-synchronizing-with-santricity-os-software.adoc[Erreur : erreur de synchronisation avec le logiciel SANtricity OS]

http://["Site de documentation sur les systèmes NetApp E-Series"^]
