---
permalink: sg5700/upgrading-santricity-os-on-storage-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 'Pour optimiser le fonctionnement du contrôleur de stockage, vous devez effectuer une mise à niveau vers la dernière version de maintenance du système d"exploitation SANtricity compatible avec votre appliance StorageGRID. Consultez la matrice d"interopérabilité NetApp \(IMT\) pour connaître la version que vous devez utiliser. Si vous avez besoin d"aide, contactez le support technique.' 
---
= Mettre à niveau le système d'exploitation SANtricity sur le contrôleur de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour optimiser le fonctionnement du contrôleur de stockage, vous devez effectuer une mise à niveau vers la dernière version de maintenance du système d'exploitation SANtricity compatible avec votre appliance StorageGRID. Consultez la matrice d'interopérabilité NetApp (IMT) pour connaître la version que vous devez utiliser. Si vous avez besoin d'aide, contactez le support technique.

* Si le contrôleur de stockage utilise SANtricity OS 08.42.20.00 (11.42) ou une version ultérieure, utilisez Grid Manager pour effectuer la mise à niveau.
+
xref:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[Mettez à niveau le système d'exploitation SANtricity sur les contrôleurs de stockage à l'aide de Grid Manager]

* Si le contrôleur de stockage utilise une version de SANtricity OS antérieure à 08.42.20.00 (11.42), utilisez le mode de maintenance pour effectuer la mise à niveau.
+
xref:upgrading-santricity-os-on-e2800-controller-using-maintenance-mode.adoc[Mettez à niveau SANtricity OS sur le contrôleur E2800 à l'aide du mode de maintenance]



.Informations associées
https://["Matrice d'interopérabilité NetApp"^]

https://["Téléchargement NetApp : appliance StorageGRID"^]

xref:../monitor/index.adoc[Surveiller et résoudre les problèmes]
