---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: Lorsque vous configurez et utilisez des pools de stockage, suivez ces instructions. 
---
= Instructions pour la création de pools de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous configurez et utilisez des pools de stockage, suivez ces instructions.



== Instructions pour tous les pools de stockage

* StorageGRID inclut un pool de stockage par défaut, tous les nœuds de stockage, qui utilise le site par défaut, tous les sites et la qualité de stockage par défaut, tous les nœuds de stockage. Le pool de stockage tous les nœuds de stockage est automatiquement mis à jour à chaque ajout de nouveaux sites de data Center.
+

NOTE: L'utilisation du pool de stockage tous les nœuds de stockage ou du site tous les sites n'est pas recommandée car ces éléments sont automatiquement mis à jour pour inclure les nouveaux sites que vous ajoutez à une extension, ce qui peut ne pas être le comportement que vous voulez. Avant d'utiliser le pool de stockage tous les nœuds de stockage ou le site par défaut, lisez attentivement les instructions relatives aux copies répliquées et codées par effacement.

* Simplifiez au maximum les configurations de vos pools de stockage. Ne créez pas plus de pools de stockage que nécessaire.
* Créez des pools de stockage avec autant de nœuds que possible. Chaque pool de stockage doit contenir deux nœuds ou plus. Un pool de stockage ne disposant pas de nœuds suffisants peut générer des arriérés ILM en cas d'indisponibilité d'un nœud.
* Évitez de créer ou d'utiliser des pools de stockage qui se chevauchent (contiennent un ou plusieurs des mêmes nœuds). Si les pools de stockage se chevauchent, il est possible d'enregistrer plusieurs copies des données d'objet sur le même nœud.




== Instructions relatives aux pools de stockage utilisés pour les copies répliquées

* Créez un pool de stockage différent pour chaque site. Spécifiez ensuite un ou plusieurs pools de stockage spécifiques au site dans les instructions de placement pour chaque règle. L'utilisation d'un pool de stockage pour chaque site permet de placer les copies d'objets répliquées exactement là où vous en avez besoin (par exemple, une copie de chaque objet sur chaque site pour une protection contre les pertes au niveau du site).
* Si vous ajoutez un site dans une extension, créez un nouveau pool de stockage pour le nouveau site. Ensuite, mettez à jour les règles ILM pour contrôler les objets qui sont stockés sur le nouveau site.
* En général, n'utilisez pas le pool de stockage par défaut, tous les nœuds de stockage ou tout pool de stockage incluant le site par défaut, tous les sites.




== Instructions relatives aux pools de stockage utilisés pour les copies avec code d'effacement

* Vous ne pouvez pas utiliser les nœuds d'archivage pour les données avec code d'effacement.
* Le nombre de sites et de nœuds de stockage du pool détermine les schémas de code d'effacement disponibles.
* Si un pool de stockage comprend seulement deux sites, vous ne pouvez pas utiliser ce pool de stockage pour le codage d'effacement. Aucun schéma de code d'effacement n'est disponible pour un pool de stockage possédant deux sites.
* En général, n'utilisez pas le pool de stockage par défaut, tous les nœuds de stockage ou tout pool de stockage incluant le site par défaut, tous les sites d'un profil de code d'effacement.
+

NOTE: Si votre grid ne contient qu'un seul site, vous ne pouvez pas utiliser le pool de stockage tous les nœuds de stockage ou le site par défaut de tous les sites dans un profil de code d'effacement. Ce comportement empêche le profil de code d'effacement de devenir non valide si un second site est ajouté.

* Si vous avez des besoins élevés en débit, il est déconseillé de créer un pool de stockage incluant plusieurs sites si la latence réseau entre les sites est supérieure à 100 ms. Au fur et à mesure que la latence augmente, la vitesse à laquelle StorageGRID peut créer, placer et récupérer des fragments d'objet diminue considérablement en raison de la diminution du débit du réseau TCP. La diminution du débit affecte les taux maximaux réalisables d'entrée et de récupération d'objet (lorsque stricte ou équilibré sont sélectionnés comme comportement d'ingestion) ou risque d'entraîner des arriérés de file d'attente ILM (lorsque la fonction de double validation est sélectionnée comme comportement d'ingestion).
* Si possible, un pool de stockage doit inclure plus que le nombre minimum de nœuds de stockage requis pour le schéma de code d'effacement sélectionné. Par exemple, si vous utilisez un schéma de code d'effacement 6+3, vous devez avoir au moins neuf nœuds de stockage. Toutefois, il est recommandé de disposer d'au moins un nœud de stockage supplémentaire par site.
* Distribuez les nœuds de stockage sur tous les sites de façon aussi homogène que possible. Par exemple, pour prendre en charge un schéma de code d'effacement 6+3, configurez un pool de stockage qui inclut au moins trois nœuds de stockage sur trois sites.




== Instructions relatives aux pools de stockage utilisés pour les copies archivées

* Vous ne pouvez pas créer de pool de stockage incluant à la fois les nœuds de stockage et les nœuds d'archivage. Les copies archivées nécessitent un pool de stockage incluant uniquement les noeuds d'archivage.
* Lorsque vous utilisez un pool de stockage incluant des nœuds d'archivage, vous devez également conserver au moins une copie répliquée ou codée d'effacement dans un pool de stockage incluant des nœuds de stockage.
* Si le paramètre global de verrouillage d'objet S3 est activé et que vous créez une règle ILM conforme, vous ne pouvez pas utiliser un pool de stockage incluant les nœuds d'archivage. Voir les instructions de gestion des objets avec le verrouillage d'objet S3.
* Si le type cible d'un nœud d'archivage est Cloud Tiering - simple Storage Service (S3), le nœud d'archivage doit se trouver dans son propre pool de stockage. Voir xref:../admin/index.adoc[Administrer StorageGRID].


.Informations associées
* xref:what-replication-is.adoc[Qu'est-ce que la réplication]
* xref:what-erasure-coding-is.adoc[Qu'est-ce que le code d'effacement]
* xref:what-erasure-coding-schemes-are.adoc[En quoi consiste les schémas de code d'effacement]
* xref:using-multiple-storage-pools-for-cross-site-replication.adoc[Utilisation de plusieurs pools de stockage pour la réplication intersites]

