---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure coding scheme 
summary: 'Lorsque vous configurez le profil de code d"effacement pour une règle ILM, vous sélectionnez un schéma de code d"effacement disponible en fonction du nombre de nœuds et de sites de stockage que vous prévoyez d"utiliser. Les schémas de codage d"effacement contrôlent le nombre de fragments de données et le nombre de fragments de parité créés pour chaque objet.' 
---
= En quoi consiste les schémas de code d'effacement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous configurez le profil de code d'effacement pour une règle ILM, vous sélectionnez un schéma de code d'effacement disponible en fonction du nombre de nœuds et de sites de stockage que vous prévoyez d'utiliser. Les schémas de codage d'effacement contrôlent le nombre de fragments de données et le nombre de fragments de parité créés pour chaque objet.

Le système StorageGRID utilise l'algorithme de codage d'effacement Reed-Solomon. L'algorithme coupe un objet en k fragments de données et calcule des fragments de parité M. Les fragments k + m = n sont répartis sur n nœuds de stockage pour assurer la protection des données. Un objet peut supporter jusqu'à m fragments perdus ou corrompus. k fragments sont nécessaires pour récupérer ou réparer un objet.

Lors de la configuration d'un profil de code d'effacement, utilisez les règles suivantes pour les pools de stockage :

* Le pool de stockage doit inclure trois sites ou plus, ou exactement un site.
+

NOTE: Vous ne pouvez pas configurer un profil de code d'effacement si le pool de stockage comprend deux sites.

+
**  schemes for storage pools containing three or more sites,Schémas de code d'effacement pour les pools de stockage contenant au moins trois sites
**  schemes for one-site storage pools,Schémas de code d'effacement pour pools de stockage sur un site


* N'utilisez pas le pool de stockage par défaut, tous les nœuds de stockage ou un pool de stockage incluant le site par défaut, tous les sites.
* Le pool de stockage doit inclure au moins _k+m_ +1 nœuds de stockage.
+
Le nombre minimum de nœuds de stockage requis est _k+m_. Toutefois, il est possible de disposer d'au moins un nœud de stockage supplémentaire pour empêcher les défaillances d'entrée et les arriérés ILM en cas d'indisponibilité temporaire d'un nœud de stockage requis.



La surcharge de stockage d'un schéma de code d'effacement est calculée en divisant le nombre de fragments de parité (_m_) par le nombre de fragments de données (_k_). Vous pouvez utiliser la surconsommation de stockage pour calculer la quantité d'espace disque requise par chaque objet avec code d'effacement :

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

Par exemple, si vous stockez un objet de 10 Mo avec le schéma 4+2 (qui affiche une surcharge du stockage de 50 %), l'objet utilise 15 Mo de stockage grid. Si vous stockez le même objet de 10 Mo avec le schéma 6+2 (qui affiche une surcharge de stockage de 33 %), l'objet consomme environ 13.3 Mo.

Sélectionnez le schéma de code d'effacement avec la valeur totale la plus basse de _k+m_ qui répond à vos besoins. les schémas de code d'effacement avec un nombre inférieur de fragments sont globalement plus efficaces du point de vue de la capacité de calcul, car moins de fragments sont créés et distribués (ou récupérés) par objet. cela permet d'obtenir de meilleures performances en raison de la taille de fragment plus grande, et peut nécessiter moins de nœuds lors d'une extension lorsque plus de stockage est nécessaire. (Pour plus d'informations sur la planification d'une extension du stockage, consultez les instructions relatives à l'extension d'StorageGRID.)



== Schémas de code d'effacement pour les pools de stockage contenant au moins trois sites

Le tableau ci-dessous décrit les schémas de code d'effacement actuellement pris en charge par StorageGRID pour les pools de stockage incluant au moins trois sites. Tous ces plans offrent une protection contre la perte du site. Un site peut être perdu et l'objet sera toujours accessible.

Pour les schémas de code d'effacement qui assurent la protection contre la perte de site, le nombre recommandé de nœuds de stockage dans le pool de stockage dépasse _k+m_+1 car chaque site requiert au moins trois nœuds de stockage.

[cols="1a,1a,1a,1a,1a,1a"]
|===
| Schéma de code d'effacement (_k+m_) | Nombre minimal de sites déployés | Nombre recommandé de nœuds de stockage sur chaque site | Nombre total recommandé de nœuds de stockage | Protection contre la perte de site ? | Surcharge du stockage 


 a| 
4+2
 a| 
3
 a| 
3
 a| 
9
 a| 
Oui.
 a| 
50 %



 a| 
6+2
 a| 
4
 a| 
3
 a| 
12
 a| 
Oui.
 a| 
33 %



 a| 
8+2
 a| 
5
 a| 
3
 a| 
15
 a| 
Oui.
 a| 
25 %



 a| 
6+3
 a| 
3
 a| 
4
 a| 
12
 a| 
Oui.
 a| 
50 %



 a| 
9+3
 a| 
4
 a| 
4
 a| 
16
 a| 
Oui.
 a| 
33 %



 a| 
2+1
 a| 
3
 a| 
3
 a| 
9
 a| 
Oui.
 a| 
50 %



 a| 
4+1
 a| 
5
 a| 
3
 a| 
15
 a| 
Oui.
 a| 
25 %



 a| 
6+1
 a| 
7
 a| 
3
 a| 
21
 a| 
Oui.
 a| 
17 %



 a| 
7+5
 a| 
3
 a| 
5
 a| 
15
 a| 
Oui.
 a| 
71 %

|===

NOTE: StorageGRID requiert au moins trois nœuds de stockage par site. Pour utiliser le schéma 7+5, chaque site requiert au moins quatre nœuds de stockage. Il est recommandé d'utiliser cinq nœuds de stockage par site.

Lors de la sélection d'un schéma de code d'effacement assurant la protection du site, équilibrez l'importance relative des facteurs suivants :

* *Nombre de fragments*: La performance et la flexibilité d'expansion sont généralement meilleures quand le nombre total de fragments est plus faible.
* *Tolérance aux pannes* : la tolérance aux pannes est augmentée en ayant plus de segments de parité (c'est-à-dire lorsque _m_ a une valeur plus élevée).
* *Trafic réseau*: Lors de la récupération d'échecs, en utilisant un schéma avec plus de fragments (c'est-à-dire un total plus élevé pour _k+m_) crée plus de trafic réseau.
* *Surcharge de stockage* : les schémas qui génèrent une surcharge plus élevée requièrent davantage d'espace de stockage par objet.


Par exemple, lorsque vous décidez d'un schéma 4+2 et 6+3 (qui ont tous deux des frais de stockage de 50 %), sélectionnez le schéma 6+3 si une tolérance de panne supplémentaire est nécessaire. Sélectionnez le schéma 4+2 si les ressources réseau sont limitées. Si tous les autres facteurs sont égaux, sélectionnez 4+2 parce qu'il a un nombre total de fragments inférieur.


NOTE: Si vous n'êtes pas certain du schéma à utiliser, sélectionnez 4+2 ou 6+3, ou contactez le support technique.



== Schémas de code d'effacement pour pools de stockage sur un site

Un pool de stockage sur un site prend en charge tous les schémas de codage d'effacement définis pour trois sites ou plus, à condition que le site dispose de suffisamment de nœuds de stockage.

Le nombre minimum de nœuds de stockage requis est _k+m_, mais un pool de stockage avec _k+m_+1 nœuds de stockage est recommandé. Par exemple, le schéma de code d'effacement 2+1 requiert un pool de stockage avec au moins trois nœuds de stockage, mais quatre nœuds de stockage sont recommandés.

[cols="1a,1a,1a,1a"]
|===
| Schéma de code d'effacement (_k+m_) | Nombre minimal de nœuds de stockage | Nombre recommandé de nœuds de stockage | Surcharge du stockage 


 a| 
4+2
 a| 
6
 a| 
7
 a| 
50 %



 a| 
6+2
 a| 
8
 a| 
9
 a| 
33 %



 a| 
8+2
 a| 
10
 a| 
11
 a| 
25 %



 a| 
6+3
 a| 
9
 a| 
10
 a| 
50 %



 a| 
9+3
 a| 
12
 a| 
13
 a| 
33 %



 a| 
2+1
 a| 
3
 a| 
4
 a| 
50 %



 a| 
4+1
 a| 
5
 a| 
6
 a| 
25 %



 a| 
6+1
 a| 
7
 a| 
8
 a| 
17 %



 a| 
7+5
 a| 
12
 a| 
13
 a| 
71 %

|===
xref:../expand/index.adoc[Développez votre grille]
