---
permalink: fabricpool/configuring-dns-for-storagegrid-ip-addresses.html 
sidebar: sidebar 
keywords: fabricPool, DNS, domain name system, FQDN, fully qualified domain name, IP address, VIP 
summary: 'Après avoir configuré des groupes de haute disponibilité et des noeuds finaux de l"équilibreur de charge, vous devez vous assurer que le système de noms de domaine \(DNS\) du système ONTAP inclut un enregistrement pour associer le nom de serveur StorageGRID \(nom de domaine complet\) à l"adresse IP que FabricPool utilisera pour établir des connexions.' 
---
= Configurez le serveur DNS pour les adresses IP StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir configuré des groupes de haute disponibilité et des noeuds finaux de l'équilibreur de charge, vous devez vous assurer que le système de noms de domaine (DNS) du système ONTAP inclut un enregistrement pour associer le nom de serveur StorageGRID (nom de domaine complet) à l'adresse IP que FabricPool utilisera pour établir des connexions.

L'adresse IP que vous entrez dans l'enregistrement DNS dépend de l'utilisation ou non d'un groupe HA de nœuds d'équilibrage de la charge :

* Si vous avez configuré un groupe haute disponibilité, FabricPool se connecte aux adresses IP virtuelles de ce groupe haute disponibilité.
* Si vous n'utilisez pas de groupe haute disponibilité, FabricPool peut se connecter au service StorageGRID Load Balancer à l'aide de l'adresse IP d'un nœud de passerelle ou d'un nœud d'administration.


Vous devez également vous assurer que l'enregistrement DNS référence tous les noms de domaine de point final requis, y compris les noms de caractères génériques.
