---
permalink: fabricpool/creating-tenant-account-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, tenant, SSO 
summary: Vous devez créer un compte de tenant dans le Grid Manager pour utilisation FabricPool. 
---
= Créez un compte de locataire pour FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer un compte de tenant dans le Grid Manager pour utilisation FabricPool.

.Ce dont vous avez besoin, 8217;ll
* Vous êtes connecté au Grid Manager à l'aide d'un xref:../admin/web-browser-requirements.adoc[navigateur web pris en charge].
* Vous disposez d'autorisations d'accès spécifiques.


Les comptes de locataire permettent aux applications client de stocker et de récupérer des objets sur StorageGRID. Chaque compte locataire possède son propre ID de compte, groupes et utilisateurs autorisés, compartiments et objets.

Vous pouvez utiliser le même compte de locataire pour plusieurs clusters ONTAP. Vous pouvez également créer un compte de locataire dédié pour chaque cluster ONTAP, selon les besoins.


NOTE: Ces instructions supposent que vous avez configuré l'authentification unique (SSO) pour Grid Manager. Si SSO n'est pas activé, utilisez xref:../admin/creating-tenant-account.adoc[ces instructions permettent de créer un compte de locataire] à la place.

.Étapes
. Sélectionnez *LOCATAIRES*.
. Sélectionnez *Créer*.
. Entrez un nom d'affichage et une description.
. Sélectionnez *S3*.
. Laissez le champ *quota de stockage* vide.
. Sélectionnez *Autoriser les services de plate-forme* pour activer l'utilisation des services de plate-forme.
+
Si les services de plateforme sont activés, un locataire peut utiliser des fonctionnalités, telles que la réplication CloudMirror, qui accèdent aux services externes.

. Ne sélectionnez pas *utiliser son propre référentiel d'identité*.
. Ne sélectionnez pas *Autoriser la sélection S3*.
. Sélectionnez un groupe fédéré existant dans Grid Manager pour obtenir l'autorisation d'accès racine initiale du locataire.
. Sélectionnez *Créer locataire*.

